# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:gzqsz+tD7ZUSK9PiWm8MFnqGiWWKBl+fPZcRCYPUgTd5yXs9+FHLcN2oSJ9wCRJitwuwUuHkvzVNg+Yz5//Apf5+Gusk+Opv/rTBBC82MgC1qhIOre/S27UA2fU8cx/IGxCzatjwPBFA/GKEjSfQ+2XFKGgsXBE5Icl4sFGnLKuyeTvMhBo=,iv:tVV/yXNY+uebxii7j6ArsQ7t7Ujkkwh5o5oGYbBbqSo=,tag:Wk6syZnPDsYH5WTi3bWotg==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:FYWenN8T+KR2qFp0pnY=,iv:IFJ/xPq7yRgqBlJIAsgyvv3wlMB6BJpdqb7xk8d/xrM=,tag:gi3uUmIg7vgWBwrEYdBKGg==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:CVaABLlHK9xGHRpOIC/rtRyRmA==,iv:xXRdaN5rgn/em1hFwcSXUG1ovaXg9izIp1YsCL4plDU=,tag:rpr4k0XfajF9q82AvbZpHg==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:f4caqTYNBRyo8l/aiQlQScdezw==,iv:1aU7GwPQwFolzx4aZstksK/nDrXGXbnsk4wAQza53SY=,tag:bEjtb+VlhgpcwXl6KBnsVQ==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:IUjI+k4eJZSWFcN5hOjJ0w==,iv:wn6Gw82TIigtVB0KaVIvJNijAcl0f9gGy6XZNJwSYjo=,tag:vfzWYg4J1zR05koucXf6Pw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bThUQ1d4YUxubWl0WWZx
        WmhSWGk0RnFFTElIZ2lPckpiKzJzM2x6cXpRCkZka3lQaGJEeFFuQnFJczJqM2lr
        akswdEZtUkNFRHNSNFZERWFsWnZnK1UKLS0tIDRGbStFWmRSUkJzV21xbFlvem8y
        NFAxZlpWaDhTU0ozL0theWNKbWhGalUKODQyAfNGNfSbNTU5MrBVm0JqaBHNE2aD
        YTZWisuMFnNMliwozhhbXQlGIMBS1+4TExFOxKatTjkxroZK3aCWBg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T14:20:04Z"
  mac: ENC[AES256_GCM,data:GbqItcQWHlb32Do/R2MOLUnqSBVFeU37tiMRcyhO0jZ9hroVm0f/xITHj18non0AzCIB9jstv7nnflpyTjtOeLJV9bNWQqChK3tkUY/jUgISJgGp8wqApKGJS7GtQ65WjbxOMWzOAhX1tLXu3SoVFwBCVBMfo4wJCKyIG1CL2HI=,iv:8zxwMezHUwbrRjwmLNckovPlcJAFYRqBkEe5Gq7pk0o=,tag:bDovKrEHp/7BH+eEbVdD9g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
