# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:PcgxTgPZL1uMrQjeMXOjQJTRJsP4mcT+An1AI8ftusqJc5L5Hi9TmWkdznfYo56Wo+JnIWgXORk4BdJpwlvM6K8As7mww8ftUVULsoEKAsepQmEiBwWsrGpFpFNYzP66ekUxrikWBbnByLYsayLJynQCLkOXvFJIxzaFi4+HvwEqDuLy/RI=,iv:TMWmrX37GPuEiDWxiQ+lMmWZKcgoDHI8gvv64CnRvOI=,tag:xBzOHLvniq0mveK9MQQWeg==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:uGqO4FHP4P6Yol7PsX0=,iv:0t9iNeQC7dv1pwZImYkMqUC2O9tq/8M4PUprZ9DaIOU=,tag:7Zr8Dv7Y6K1b3fOiGAbJBA==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:xVrzT1WosKJw2kko6fUCfkycUg==,iv:v4mXiI1PPScixFfO0163x8mOEtW/ExKnaSpJ4OBVD5s=,tag:YOOCRqtS+OLCiT927ffuJA==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:uip1HlDZC3WLEAny8bc2RlD0QA==,iv:Rk6FzvExITvJfnlNPqQoZSrfjGHm7VM72NuHRiYceks=,tag:PraRnwxqbNjZC0vwU1jShw==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:jm6EdFjXu9Yd+HeXM01/1g==,iv:qioPT2D+2H8mz7q7eIlgS4+o4w8DsO5KLfIeELVx7Iw=,tag:uJklDjI+xJe6RDxriAMtKA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZ3ZtckhVWEErVU5yb3RE
        eVY4amJwdXk4ZGZKRWY2ZkdXUVZhUGVCK1F3CmlzRUd4WTBxN0wwbWxJZVBoNHox
        REQ2cHJHa0YxM1UzOEhjdzNyWlNoeUkKLS0tIDJ2SVdTWElOaFlXY1U1eVlCMWlN
        NEpGM2Z6MmVpVXJ0Q015MThCazRGc1EKxoQi/LcsuBmwULddJPZe0pNXTbgXnloC
        52t3/BA7TNfvqhtuQa7mbncxIQfitSB/G4VkULC9YCJNcnXTciD5/Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-25T12:10:13Z"
  mac: ENC[AES256_GCM,data:7dSdrWofdfLo+bva95v51PL298WSWiZLT8IEOBN2ihzzZQ3R2XDix5f55fdIYXWUJytRWSC4mNa+2fTJcbyCc/WL9lgGt9DbGAW9WqTAop6eWLRfBP95g4AcPw571LLD+ruipRUWY7FEyD7ifsq8VxDWvPbB7CBpQ5i0FzLmWWw=,iv:uvDMM4qLedaXBV4X+LcgxJ3p57GTkU9IsRXKmclglsI=,tag:fA2sxuoq7RIZJmadb6FiFg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
