# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:9m/QxkUnI71b8paNpzPziNdL+FKmCxl7AXCwG1Qt90slzWNN2EHghFGjdfek8upyiLMgC3/ZoMOaXfhU2OJnd9yvYEZiJaKJbpwVe0qZok0OK8lcJPnmkF+OnOdIYxwLHZMxOV0LX47bBP1oPnklvfJeMNsSzmuC/BSWELDke4CntmdoKr4=,iv:gMBtlYN6cPA7lO6m3N4nYcIhz4IlZfB59k2nvaOvBJU=,tag:ZB45pA+q/BpQXsmnJ0AQDg==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:FumbEta9O0Hd3c1W1Y4=,iv:6c3bcqQO/dc8FU92x/GWbpK84aNw2oLeaAgpCjIArA0=,tag:zC1ojV5bfJS14vZlYPlm+g==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:/UQ12naWm87dpVqQMRLo+RKpWA==,iv:dDCe1cmHAzGK0cy2ZQBd6P4lubMwle+0lwejavhGPDU=,tag:utRE3JOEHAMBoppA1QcTzw==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:hTxQf6MiV/ve3DU2y32+LdocYQ==,iv:YKIJgHrmZVbMJAHpF1Y6F6KN7uDOTAyVtBw5mOPITvY=,tag:i/NafcUYALcLzYIx9svQHw==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:sUzwHH0+4J23az0Yyr+5oQ==,iv:DZTikPUuZ2CzL24Agv0cjJ0r36tAqVCYkU7GhH1jDy8=,tag:+TuL29ZI59opiu5w/safDw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDM2x0Lyt3Um9VUGMwL05Z
        YXpoMjhNUnFFU1lpUnRuS0phTGoyNUMxSUFzCmRObC9HVEFhb1RjWm13aFFaTDFh
        S0xRa2ZvdlhpZWVCa3ZsYVJlTkptTjAKLS0tIE5ET0RmSTVaaW5MTnRId2dSa05p
        TUtTQkZWL2YvS1FLVzR4K0NJTVlsVnMKpALNFQPqj1jz/Mh/8yqZxtsuG9vONLVS
        5FxeMJCp8DFeuiKC/lFDUFVKokVpq9B6tqamTcxJDJD4yKXiC+Pd/g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-19T03:45:39Z"
  mac: ENC[AES256_GCM,data:Gcvn7zDtaIdbqbJCrYvwdHjX7a0DVS9MKuFyYggtNecOeDc5Kt8KyMz90dCMlhPdhKebVZx3FqZ44IB5IXE3zW/Z2uf12/W73Q/jUMcPqL5YLEPHEK4phyXiKgAytS9d67wSESkXd6kydQVGq85AGkr8IVj51G1Rz66TUAceg9g=,iv:nVvpiJY4YDlT1db79Qyrcb07jNIVUsHqX+2TjQsLpi8=,tag:qhJY09WeuovQ0dYuJ6IioQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
