# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-secret
stringData:
  idm-admin-password: ENC[AES256_GCM,data:sFL7tHndmzAnagxMDgCHVY0QeXA7fUNzEvAA,iv:3gqOQhc8bS4jDAWHeJkHytX2RuS1bkj/R6souP8fY2Q=,tag:lkwFYP8sIL6cfUNwVz4O2Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVmxPd3NtcjlZVUwzSENT
        enBOMWhPc1NXR3hPZ2l6T29hT09RMElGNGpRClRIVXNPRVlhSHBkRWNGc1lreUI0
        ZC82eE1GcS93N25oVlRvblJXOTFidHMKLS0tIDE4VmFyWXpQZ2QrYVI5UGtMMy9x
        WkFIVVVHVGhTb0FCdEx2MDBkVHdtbWsKNtHMw5OpjjD912ipth9tWRQ3gjDGz+nd
        HnpUVDa0qj6jVZEV6rqt7qSB5VkitIRCwqp3wwdPpgREtA8q2KTzkA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-19T11:25:39Z"
  mac: ENC[AES256_GCM,data:aYsMsgMpgwmnmiYuGURm5M/bMoEFawP080F07X6m/SVFzEP3TXolM6ORoTZD6YzkZyKHmAPGtziWifWQuYFdUeP+OdATv21yCtGHvHdIf1q+L24ueeYbqxR3uy8YMj5g+FXWVEGXlS7WDqgXhZrxADEYVDnrWhfD2anBCh66XHo=,iv:NzoipsE4DwRtDR6huRxF25vIDFYZ7KLaTGvgBUkeppI=,tag:+bdoCx2fzM6Fryx+8NMv6A==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
