# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-secret
stringData:
  idm-admin-password: ENC[AES256_GCM,data:bcXp89v4yPPMDMs5/BaMhzTtm+cHyLSjw8kt,iv:U/I/zSpR6xQl+Dxc7XQ4EIMyrebZeqDuaKNSGy8Pyzg=,tag:Sncs14az55sthk99qOykig==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBL0hzZG9sMnNxc1lwYmhH
        Y2VzZ1JRRUErM1ljMGF0aUpRWXNhY2V2TUVNCmpsRm5EUGw2VXZlcjlma1lMc0tO
        YzdROXEySEdxV1dyUkdZSXhQc3lDU28KLS0tICtJYWFTTU1sdmxIdXVDdlM3NkVx
        RjFUNFAxVTRQUTEyOEVkY2c0VEV0SUkK8EBMf+NKEUKd2DD+IGbGMw3jSvV6h22h
        5NfgCIMC8sIV9A01znpUBRwVN7mW8Outl/ymaU6QWawHvXEK7idBeA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-15T14:45:31Z"
  mac: ENC[AES256_GCM,data:JAkPJMVVCaeme4kXD+OCJSdJ5rwR80seqk9/L71PixHmLZPVtGfsqYG6O4gGQytxiV34fE5ci/vDFtq5Yd1Gw1ldyLHyCgxrvm2isMO3NfPO5IpMnk9o6yfB9nF9DtzMAv0e/Pq+6ahOmXLbCgANZKZGVGa21c57VAplCcS1rnk=,iv:KqfhPEZu3iPRFoibO+KefG1UqBflG6/DTBVA0vSxYEA=,tag:UnPLQWS9twgJpOUEKwT3aA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
