---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-secret
stringData:
  idm-admin-password: ENC[AES256_GCM,data:HQ3CDU/b6rF3GcRL1gU75jpYrQcEsm9yl9jr,iv:s8TnbqiyE4JLmLdXAPpTbFb0vU1H+FWKEPNy6Y2XhxE=,tag:f9uGYuvs3/DaaBaYMJgX9g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkY1dxYkJ2OGh0dHVSK3NY
        bWN4ZGUzWDJ6NzN0NXdlRngxUUR0S2Y1dkFBCndnSEhzMGdhNGVDakJyTFpuK3F4
        cHB3dUNWdVdWNTY4Mjk1MUlaSFRMb0kKLS0tIGVFS0xibFVpUDZ3aFQyanJBdUJB
        VkViRUZXczZ3RHMrSUYyVlI5TzdrbTgK9ribNY2BNvsVD95h2/p4U63pFKZF5oo3
        LuUPptU0uNa96NwyKCX5WyqBrVWs+InRRWqD+5Ru6ioLCk4MDq0L6g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-15T14:30:52Z"
  mac: ENC[AES256_GCM,data:RFnnGTeJyw8GtItEQTsf1imR45QrEQxDPBP+ZZApgek+a2j87HukmNi36Dk+KDLgxmVn2O/OW33EJKy4+nfbmWuidtJKMIN6w9iZ76upe8VNOKLSmVPyRTfwJyqLqZeG+b9h4CzYBHQ0iac4PrWwzpGeLX2V0q/5n2CYNXCZ92I=,iv:NWxhlUHKRCGigsW12C0p5w1Jmy3fH6ptP3vvPViXPSY=,tag:yUaB22nakI2XTMXHvS4Wfg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
