---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
stringData:
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:GXKGwM5u5AZ6aKGMrtattQ6kbSCC,iv:qHaI6GFg6+/wbl4O1M6t649FU00sDbzUsnLUWPh+B4E=,tag:77Y5y3G/XR4uDLdaVTHznQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SHlpSldXQ2ZCaU1Gbjkr
        ZStZc3AySSs2bkdXQ3g3UlV4NjMwTTBucnlJCnd1c1E3OGxoSWVJV3o5WlZSdDYy
        NjdjN1pHNzB6OG1wcTVmazBoZWVWVTQKLS0tIEJVSlY3ZDRtSW1tMEtaazVCeGl4
        WkRFd00yNlFLeC9VR0piMEEwWEpTRnMK8UyekX4iub6nTeFBbvoqTSkwO2QbFt4I
        6QGu8p+jLLrgQo87cBmL1f7c6fnzTHghGWbm/YZqS1uR/ZK8rQRmrw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T19:57:52Z"
  mac: ENC[AES256_GCM,data:BnxHRWPFwDq6QbQoGAFg2DPMoHkKGXlpMPs/1/QGKBxGbydlf0A34NeqGNKt7aN2Ihmf0poV1GjGk0UQz7gfNl8ShqeUARJqHBoNenoxGNypR4pydrrrTLhvzD8eQRtEQaANbNaJO1xkZ4CojSZNa5OEb8Uy4omPRvemMt89Mxk=,iv:ImvGmk5hYqeo6uQ82F7t5hsak8RVyQ2i+auKNUDJSMQ=,tag:tBTzyL3t0l/a9ps+Y6qlJQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
