# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
stringData:
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:6NvU9AduVskuMumjSYdTQHxeBxoe,iv:ld//nHzo3I5Z5SB0/VxzWIbrw1xk7vHS/Z7laXWyZN4=,tag:taMzvLiUpyHggIReM4kQbA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUjVLeW14UnRWSVN1TGp2
        eTJONXJ3M2c5aSthdGdJakdqOHU0ai9nUXcwCm5YZjV1eHlFYWd3VE5jYXlMNEx3
        bEJMK0VWdDZOVlZ5Q1ZUNmZuNk50TmMKLS0tIGhKM1hnRXlOSlJmWk9WUUNGMDc2
        UUU4NWtncjlGU3JrRUExempWTyt6cEkKKUEG6IahXRXiBpHC3mTpeZfwqLNslbK/
        0KADkLJ0pet03ElcphOEOATUPpZlFFiEH5BICpFATz+XDo/Wiwoauw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-10T16:42:47Z"
  mac: ENC[AES256_GCM,data:z7hAHFNKBqJcnDV8rRw7GBwSKopH9w0tDDCUMmr8K2E+KL5vl/Muoh6cQydMI/W6xaH6CNaxg8nxFRawVOFvYHohESPrWnw9h8TsKJHCbunO+KqUiaOKrdb4E2ABvVUPnvDVKsZg6GFBZXi7W7vpI9OojTNkDKfziAsy8/4WQZI=,iv:5+TzIEpHq7zyKQ3bhdfx9X0nutvEPVtLEpT69qhCAX0=,tag:6Nq2G865Ohlv3Ih7/1JGFw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
