# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
stringData:
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:3pp7zOOEx0YH9DdjImLuhR3n6HjH,iv:TunYMXIdykRvUETx21XGo66bhCbImJH9d5G1rOU27g0=,tag:Jbxt6NF61udaxYpikAsP1A==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eHBlQ05EZ0czdFhSN3hi
        OFN5TSs1QW5WajkrOERQYjNGbUx4TjhaYlR3CkNxYytMeWZ0TzZwbmtxUnpOcWE1
        anhia1NVTm1WcUw2M1dyT1Fqajd1RUUKLS0tIGh0a3M5UXBIZUViVUNSWXN2cjUv
        K3FTaEtPZlVhYjdvSmxIWGZHdlluZVUKxLfJFU7fhUvXu56UuZ7Fl0pzcje9TJ2U
        +t2tPlrkbhWWFoQgz4NpSTC8ncwBWBZNOaZc46yr2XMfb/NvOdfg7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T20:22:42Z"
  mac: ENC[AES256_GCM,data:BxsVcjaGGLMOfomwUXHVYnsDavCGMpudkSDUacthSXoX0Gdcyu/TNITMfdixMczTedolejZQmP5n1y6l227t+jWrHSZM4xlGhfQ3tsOeVgH8lNZdrIOBQKbaZ6aZedEBOBcBGkZU773CJ7zgfHKpfaqUTJLnMzmra3Dq6aKvx1U=,iv:u4dDT4s2P/L4ilxOSaQl1Z8qvhho4h7/THW/cBq9eRM=,tag:bVdsMwUhE5jEKrUhlZhgEQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
