# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
stringData:
  username: ENC[AES256_GCM,data:Bfy0xiW5IcQ=,iv:0dP/bnNYSKHCTboxiEu9kbQNUcOsfjtkFBS00ZGcDp0=,tag:NPUEvVhieL1gvt4YeX6Hsg==,type:str]
  password: ENC[AES256_GCM,data:Ry3nhiC91gc=,iv:y663E8lrZU/ZlH1yJ5wcTrOF9/Ag2uiCRWiB65Zvvac=,tag:kpHpQUXZETLRnAndTPcH8g==,type:str]
  ACCESS_KEY_ID: ENC[AES256_GCM,data:QPPDJBE62V+705VfSuerKDrXu7I3SYDL6Tw=,iv:E3gIApu/d0JPoUgh/p2C5qF4VM6XmYMYUQQmURiV/0U=,tag:WHCB6ZFjmdo6O24p23kXPw==,type:str]
  CNPG_BUCKET_SEC: ENC[AES256_GCM,data:n44Vq6KcEluJ5493v4aRdnxYQ6M9GFJjaICQbhdmU6p/bBAT0KYgqrZrn8NFCn4Iic5Bqk23C5gjGqWAXIzQNw==,iv:SBxwEtHZ6k5tlMqQ5dcvvcWym7AiQSe9CACbldLyfw0=,tag:nSs0HDouwmcgm3f3pFUpOg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQT2RpVlFmd25vZ2d2UUJm
        R0Nha21ZY1Q3NFdIb3Q2aVlwNVhBSFo0OFdBCmZTNzNYWVlXRUFONFFwa1JmdndW
        K1JXZFEzQk5ZZmFMdERnSzlJWmRWaG8KLS0tIHd2MHRuaHBja1NCWWNYZ0NxNVh1
        N3R0bmpLTk5YdSt5Nm1YbTRVNHB3MkEKRg4wjZKBzxTea8yYQhkvExCpLcEWKMMp
        xm1fOc2wy1J62HaGPQYOuupJ165l2nQNRKKpTaRbuSJhk+ClTekz6Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-19T11:25:39Z"
  mac: ENC[AES256_GCM,data:gJybTHiq9V5Dr8TQBarDu76PBFqFtdN0TYxbIKBOAHsuJuZqjs4T+1KVUX6E05ZGwevF+eJU7KG4kh2QGwHxMvoopRETIUfyuPh9TfsVsAObnSXjCBzXWD/q9m0MxZl3MLiN1buJoMiavHtO3Y6rakmjSso73nDsNB83IOrhv+4=,iv:+SnwKOdNpyfn4Fr8ykTp9Y2ciTwS33cVvFo/AMAIgdY=,tag:K5njsACNaEdqJ0zojcli1Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
