# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
stringData:
  username: ENC[AES256_GCM,data:2coD7QcwLDg=,iv:4XZuGax4rSL9aAZCiDv4deqmY3v5xt92eQtVroBjd18=,tag:I8gDmLVHrRHLVjhBFmhWqw==,type:str]
  password: ENC[AES256_GCM,data:Sh0C+Wv/0yQ=,iv:0e7aGhO6BQdWYRjiURpgYr3MVk8O69QiNpOnryKa6kY=,tag:E7zQ50e7WorhmhHU9vS6pA==,type:str]
  POSTGRES_SUPER_USER: ENC[AES256_GCM,data:OPxDkw+EO/A=,iv:u84StnoZCivUx4pXhiHgZAfTdhVE43nRZ+LGuZCk+ck=,tag:4/ooAxwnQC4alXr5p6hFJg==,type:str]
  POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:S+iY6aEze3g=,iv:z1oy3290p25u+1hfXtKu6he3Jer7OpxL88KokQdpIOg=,tag:761+0YYR6DVJk3G3lO5nCQ==,type:str]
  MINIO_ROOT_USER: ENC[AES256_GCM,data:Ughpz7o=,iv:BlOJQcng/hKwjnCkHCn4xpjSkoHPQZ9tuc/AXiSEsq8=,tag:9S/8yzajYGzwQAvguACkkw==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:zpwUzBagIpiYQaFh+LE62yBCGeiSI0c=,iv:A0Fihtv5LYf3Wk5gSG7yThiGCtr0L7UfLC8TSb3wg+U=,tag:uc0kLYnW3mNxJD8pH54Jiw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQzJBVFJqdVA3Y1pNeXZx
        ZjR1SDRFY2FYc3d5TTRJVlAvb3ZJQitPUWxBCkFpb1Q5WW1hNVNTZXFvS1V2eDNO
        YW8zbHFYUG5oYnJncEpXRXZUV1RSMHMKLS0tIDFwT2xwSG9FaU55Tnh2ZkFFbUZ2
        bkpOMmFIalBXekxxUW5qck92aTZwZW8KKQOhbuxthADJe1aqIH8R47AeU/JHLuMw
        gl2Y/3yRIyNhbEIR0bSs/VcJwndysb6KlKiHokz3GWvOptgaFpnE5Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-15T04:37:46Z"
  mac: ENC[AES256_GCM,data:8oM4EGJ3N9u5Bm/Cjc1BbgnrXDMpEsb/ALGcOyCVKT2YfYWarxXkDTTrmxu4tLVhYC3wdWKEPi5dqMC5qzvqeZnTMjX+q7Z8UxYt5tTrXDhkJM55R3Uz01DHSzYsx0XXpaO22ShljoFtM1lG+tMqkTE4X/pDmN7IvVAqFamx/Qc=,iv:P4oxqY2nHhm7L3bhcrpmZDfSrFIIzucEdFniaj5tJqQ=,tag:gFq9k0DBLiSUbmWbZ8ABwQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
