# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
stringData:
  username: ENC[AES256_GCM,data:hR/lMU4dhic=,iv:HW75V0GI5QzT5i7JbFwMLD1WP/U6jD4LzNeIr6wd8dU=,tag:0so0xMcURbkoCnVo2lJWIw==,type:str]
  password: ENC[AES256_GCM,data:ZAK+e6Ur5tI=,iv:UrGNHClj1Qwsu4VNKN59gj31eBmdLLLJetJ2AUr/Lp8=,tag:QEFyJRCIpQJNV/O0NvG9tw==,type:str]
  ACCESS_KEY_ID: ENC[AES256_GCM,data:LejUfyRj/xyDH+4ccc1bSDE02/2N10XDj3Q=,iv:QeGKysE40oNqgSKbh5+epkCX2wRyXt7I2KnXP/SMONg=,tag:BK1+IM5CjX6zA1SngQitXw==,type:str]
  CNPG_BUCKET_SEC: ENC[AES256_GCM,data:NtQrw2t5HECGeC1UQJLWZ+nYJLW06eEPF4YSpiPDy0kvQtkAuWwKJrNACahPzd8KaNkrAziSQx264yTY9gSU3w==,iv:GMIcTZVwkchAnSgxaa80B8gQjJc5tdTeRI5aYG75X2Q=,tag:/wm5L6a8PaksbnLrHgZ26g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNGdqTlBiY1E1ZUdRUE9X
        NHdHNDhJMnd0eEp0UEY5cy9hYnJaT1cvMlVFCnZQVDMzK011eU1yaEdFeGsyN3NL
        eDdBY3B1MkREVFZMZ0dpNkRJOGVJUFUKLS0tIFZCM2htMVpmQzNQSGg1QUxWUlNH
        QVZLQXZETGtDb2NHWkFCOTQwcUlUS28K5Xw81VXLO5zdbaFUSrkFj+lsSu0RScUQ
        acA/3iVKZauL070t5FtAVDUXha2gHtZ1CD7OoOBHemM+lbebiJeOHg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T14:20:04Z"
  mac: ENC[AES256_GCM,data:TctY+74iRumOgeEbvry50M6UTDCR43Cp1f2DGTxlpVYydUM+JMEYrJUL4jmXw1sH0joTzeQQECrPKuuffp2KaJD9G6vRnI95PvSfQpsijDHkqmt16IupBaLAqv6wRkV48pVyIsidudMc+/X08rIkZdyB7dWkuqJzZ7nxtntcqZE=,iv:uwhrgIsgm2uQpro9AR5a6J+Remn3+F/IwBlXvpVNIEQ=,tag:+gYcClUM4yj6z70YJYspCA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
