---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: stirling-pdf
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: stirling-pdf
  # components:
  #   - ../../../../components/http-scale-to-zero
  interval: 1h
  path: ./kubernetes/apps/default/stirling-pdf/app
  postBuild:
    substitute:
      APP: stirling-pdf
      APP_HOSTNAME: pdftools
      APP_PORT: "8080"
      MIN_REPLICA_COUNT: "0"
      MAX_REPLICA_COUNT: "1"
      COOLDOWN_PERIOD: "300"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false
