# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
stringData:
    TIMEZONE: ENC[AES256_GCM,data:NaqgWw4Pay2ZBENiFg==,iv:NuZKWVpXrwQ6/ZXKWJQ/LtobTrNKnlRhaTS42cIO3Dg=,tag:sI0jwKh4wDQsAaAhhVeCMQ==,type:str]
    ADMIN_USER: ENC[AES256_GCM,data:Oy1NGBOo,iv:pQ13hnT5tJ0x4m+HfzcRhS0wli4xa2/L4L3qLexG6g0=,tag:zd/5azlZErOe8N+vXS+Sqw==,type:str]
    ADMIN_PASS: ENC[AES256_GCM,data:YfKgC5pU3cJAFe1ezmHfVWJMNQNEuQEQRAXT,iv:5EKRM2Le64F5eTav8HFzRFwFKxhHcimtLg9hSUGQnsg=,tag:jOKtUG8nju9wsdVXYRGFcA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:LqKV3xIHPV6C,iv:HqTMQV0u6JqZOUZcjDpn9wtaejuHNUOPEcj70eBojz0=,tag:Jw/5PEG+3HTC7cTpykUimQ==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:GlrkwxvrB4c8/PG8UVR2cccUm27E6n/8BFqVgAhCqtZhZfM9x+swyHtGwVg=,iv:QzeljKciM/64DrKtEXX0/rHWlInH0KCQFOKaipHYAlA=,tag:ShULGUPwlhd1A948b1lGmg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:iCR7MpJahy4=,iv:RT+fidCIRutt5ZOt9o1RPRYD7NIk1L8Apo/YOtjGXwE=,tag:RqZt6DwkyRpNprcoy7U72g==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:DDxs6QdCHuw=,iv:S0s/v0SscMJBRrS8MlcZmpnL2xh7iMAg30ThCi4l//0=,tag:mT0S672iLVizMip6bZkDHw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:gk7Ft86iKUU=,iv:KoJ4sQf1rH41d3vIXrKYt4HKsFAtDNF4cGHbSMvuBZA=,tag:y469tg0TbEPUqx5vikAN2g==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:/13M6PbT0wZsYnPf7Dg=,iv:72Bh8dn2z6iw4T7zLMPkSKRbkE2Cn1lM34PjRx/hrEk=,tag:A1jiFLhDw8PVKgz/SkBsFQ==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:WP98F2O3t8cz,iv:+cqx/8t88lyo2iA1QVh66i8yreB/dGj20BIKKsBztpI=,tag:Uv7duANvuY565pAGgwUK2w==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:5A5iF8WTUSfEJtMGHmHctFtQMg==,iv:iY3x1pVp1gpRUpmtvHMoPK8ctYtZOLSwDosKaE1b8qw=,tag:I+/BKpaRu3I0snszj5FQog==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:xYzVej5fpDM2TsrX5529jg==,iv:K2QMpPZv4NVe0ngiNM66yYhn+m11WNwlO8LNuRtdtx4=,tag:/vQ/D6xMdr6+rZSG6dXFnA==,type:str]
    MAIL_DOMAIN: ENC[AES256_GCM,data:d52cUL3Ylpi+,iv:7HIjzaukxCKJm9dYz1fQ/hRTf0Bk0lkAgmh2kOy5dsk=,tag:0ldiRz9VVvTKAVd+SIU0mQ==,type:str]
sops:
    age:
        - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MDAzUEtpRGhrWFk3aG5z
            RjdKMGNlSGQ2UEZDMHU4VzZqaGVjYm9EYVRRCkdlTVdjWFJRUUVzRm42Wkt1RlBX
            WkY3TWFJeGg0cGhWVUN2ZlM4ZjZuS2sKLS0tIDVWRFlnUUFCc0tmbzF1aGd5Wlli
            UUcyN01KazlpbEkyVGpYZ1hJN1crZW8K0acPc80mYGvDyoBBzHgadV4D4wo1Kk82
            ADtnQ4YTwn0OWG0tJKCOh/jv+ft4bWRgTT3wVxB+r11n6b/Kn9CDkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T13:38:49Z"
    mac: ENC[AES256_GCM,data:WLMp2VDtjgX0J7uWn4TAsidKnhU5p3XGxHD0t6eCdOaVsGr0RRNrd/Eh2L00SmnMzTSrXyktdfXo4bxzKCqcdli5gQu+Y6zCYQfvLqK4SPu+a/vAz2OVceJl0L/yStZYGSO+o9OXvbVdLEzVQll09TRuCkpZpprtAPme0iAqDek=,iv:Mk0HS1NYsJOHF/JXcinCgjyqFbkPJIKm2kiGLejetXk=,tag:8avHDJ85v0xPPEG/hB0KnQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
