# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
stringData:
  TIMEZONE: ENC[AES256_GCM,data:1nT+n8QdkC2zmpWWrQ==,iv:bwcI4nUcaqn9ksywtq79ccyNfOqwdMKiyPi9kXV7Y4U=,tag:wnmaAVZBVPyV1IN9dNW25Q==,type:str]
  ADMIN_USER: ENC[AES256_GCM,data:Kbo6eq1v,iv:02v8/yAKjDPTQ0U8+pw4xcPBwEfIvhIaJ3MoFJh1IFY=,tag:UmRVnR1HrATpGwXOPM3v2Q==,type:str]
  ADMIN_PASS: ENC[AES256_GCM,data:3gsEgplakG5SRmtcoGQpQ9DdVax/uLy25E/T,iv:QBHfwj5b+Tchem59theeydFHhSgMfRg8NycLi8DHDQY=,tag:i3wHFevHDYm5bbEHsEmC0w==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:dUDSwnhRoA4J,iv:Cei8iKwR7xax/LI9fNcK/wIXN2AstYpwctF2gekq1OY=,tag:ii7Y7yQqF28arEZzbC9Vtg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:LReiCIIRbEBtjLB0bHPT0OMpSnSiNEJsv/YfwaMmNKiwXsrAjF7iOx/CKUI=,iv:NirpweR27eJDHz9Mfv0on1h8Y4dY4CyqcXwUHtg/fyQ=,tag:qFJ2iOIK3v0v7SC69CHo1Q==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:Vzr7UqqfbCg=,iv:77JNKZUTSPQoYiKpn7hvhVd7CXgYYqhaj1OY+yp5Yts=,tag:Q29DeaMmCEiBdQx4SNGCXw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:EIzIkrKvu6A=,iv:lAd+/E+eg+qtiNuHiGUVdk4KHlmOdncr3zuOiXgRKdk=,tag:caiGhovh1JNZRtC6m9wMMw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:7G7Cblg+jZU=,iv:ASmoNll5xliYfw+fHs8SItLq8lDFxiaJhdk1avfhq5o=,tag:vOIM4rdeJYTQOApGCsPydA==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:SBPoXHZDRrrrozHZLHI=,iv:trRfY9y1L0f+5G9Ud2ocTPBEXeGM8aDZMWcW2++OEQ0=,tag:cxdViCB0+llcrDdZwgQWqQ==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:mtllsJNSHlyfi0jhCBc/LQFUyQ==,iv:eOLDu+ucfYNjnfeQy3OCYZq9JxbbNBYnsRN5nV4o3sk=,tag:lN4MXeD1RMJ8EU7YtFzoyg==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:E6ldSDy/DiTlojR2MoTmzrXLCQ==,iv:XD2c3xt6AuJxT+07CWyV/Rsp5kx8JKYp9FfHu2hylt4=,tag:mNZXolFHUGaTriSYoXthKw==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:5w4rI4sFzI3+WTvu87KQOA==,iv:YO2OrbUU2VMEIF49Nctv7uTn7BOAwO7a0/psVbkjxS0=,tag:ol7NCTo8MbNRbRPjMETGSQ==,type:str]
  MAIL_DOMAIN: ENC[AES256_GCM,data:RroC7AwibX4l,iv:oFTFs/qkAm6JtQ4RHHtpaKJH8SRmAHm7OF7J5/8LRVg=,tag:a13yDmGF0r6ZG4Vf7by9rA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRjlDcGQzOFI3cVlCdmtQ
        ODRFd0hIcCtOMkR5dTNOY3hGbXpFdjNWaGtZCldUM21qK3BsdVhDTWxIOFpaMEtx
        ektDNzhseHBVOTJjWWtETEFoODNoeWcKLS0tIFNENXZoMnRlOW9xdFI3NVlyS1Qy
        Y2w0RUNMRWxVTjNBMm9VYi9mTE1uZlkKvJvAlISBmuDP6GO+Urp3wUhMUe+wD3X8
        iPa6G5taXT7tNbnqt+EowbiSHp/5SUJkLjT3KehqTTZoN0sWrwcskA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-19T19:35:04Z"
  mac: ENC[AES256_GCM,data:EyRpD/jxoRKTrE4GOxMVFoXUhDvmqe/Kp8MRA7iPmBcmIz97xlSbsYEB5s7D1mIFM2vPs4illTiPlgFUkvRrF5RwuTYc+5RkY0+6ux7MGhTRJ/z4U3mUfAa1OOUrzWZ/7Lo+iKjZb7LvEcdfgt4yE/6ZbEHhsgLrRN//aT0H52U=,iv:rS8MmBbbESzdBEwJugsJyzS3YFD8B+b/0q9gwcAUCiU=,tag:ZdTHAGjcQ92qKKqRUSr82A==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
