# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
stringData:
  TIMEZONE: ENC[AES256_GCM,data:t1I7VMTTFFcvmWcQ0g==,iv:LEFHMiZ9of8Db39y1TcXRhc6Qgvi48fWS4+rzZqI0Sc=,tag:4ptbkN5dyihPAVdqj4yNKA==,type:str]
  ADMIN_USER: ENC[AES256_GCM,data:77b5r7rB,iv:+X7ZKU5TibE21tVRXnRI7xXrx/L9aIka73cN82A68R4=,tag:6ImhnmjCyeQfNnfMOSlF4g==,type:str]
  ADMIN_PASS: ENC[AES256_GCM,data:VOHWnIHDBXH8lWSzp3zWpomQwlM3Kw72SHIo,iv:Jg9dTHgWredzwIowIaw3cvCdMTqDSeSZRpQxIy0NiU4=,tag:Gh/ZT8JvEUkrPw/Tf1eMgQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:bv/cJu5nPFo/,iv:DHZtQ8Ja5WY61tUfZYMCRYjHqlJSHD3S65mfw+NYhOk=,tag:e+jXdaUZ7xuo/lEm9XNMqA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:jatMEFjpX34XDdrhD/ZZBZunN2nNPO0Ov9x+ikp5o3UcHcG9ruHIiDVMSro=,iv:AO+be9Mh0B6RBLT0tjInqskQo2KB4PrFYcVBxbgiZcY=,tag:/AoreH9UaEriqHmnh5MvWw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:+CR6d565G3k=,iv:shDAAdLbuWIZ79bP9rV6J2H5KOj8bwvCmljIJkvgGlE=,tag:d+cLncgWFn2mfdpeTcF1Rg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:w4tcoBVg88Y=,iv:LeFJN+P2DEQyv3af2DMk0QMvH+8N1wcD76kZrnKLIp0=,tag:PD4cmKIwRA8hVWx/KcwQeg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:szA8vUEMKQ8=,iv:knya+WEsaOPYRtWo5/kDaRRqGvds1xBrGa1CBh+ZKVs=,tag:R7kdUzWlzXEz6oZCBKFHGg==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:6fW1BG7v+x19324Kg4s=,iv:LWNrjl5RpvDp0tRp8C05grIpdjM6AE91EYUlV6Oxtd0=,tag:SJuGsKPsukBDVYGMEx5SXg==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:kuMFgPWRy0s5QVQmpy74RxCYRQ==,iv:F/sz+zquesLRvFReyFeXj5nKq4LrP45MP+oP1wx0WXw=,tag:Z5AlInl+3/85TUzvthk4GA==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:ugclTn2AUeqsQKWm7J1CBrUtGw==,iv:0zQeLqAnZSbRPk7BMwfVIGCn3kOkZMQ+VyUfFdC3yNQ=,tag:hbT8zEqgKHfOSL66ZHrZwg==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:3UhzAWVWSkARsSBS0R1piQ==,iv:tGftNFrOhj4k4TcH5BeZYBHdDluyQEj6CXp2p/SgkZo=,tag:UoaJWEe/3B2epvVjEwniuw==,type:str]
  MAIL_DOMAIN: ENC[AES256_GCM,data:ltwYG1m881RB,iv:Teh92Z600RzDNAMkRGWWjSNLSjbAhHjcTLvxUPCh/hs=,tag:tg1UUS0nEhkpLvgumwewdA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbk5PSTNoUmM3RGdnZHFG
        TU5UWFlGejdIcTlBRE1nZFBNY1VuNUV5MXhNCnZIeUNpUGdXYmM2cnNTazRhdkgr
        dmVyUEFPTXJLaWZQdmp3MW5JV2RmbW8KLS0tIGFGTmRHZG1FbWNHZ2RETCsxNEpJ
        NEVSOTJJSFF0Y2lYOWl1MVFVQWVzejAKNaMqhOoQR/g24zRDq7LGq6nAS9KwoLlr
        SrX6iBqv9EqVCWHS7F5M1YmUBnZpOVenuFf2x7NJkd2gvM04jnjuxg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-15T14:45:31Z"
  mac: ENC[AES256_GCM,data:hTN9Vn8d4HG36L0ac2vQZxPCSLjOCJrsDv4ttxfJ/MNkvVxQEA7ankXazwbtMRAM4K5ryW9Ou6qWwuNi55UX6bhz97d23W/Gz2thcENGbVpnNZAIwofBR7w8f4jTF7q/komHB6g7WBZxgt6z/2qHjya75fWwI5yw/vz1AkEj7KA=,iv:uZWkRXe9im5z1csTwVh741B1oc3ZmrhG6lvmYC7+6Hc=,tag:s8F2Gw6dYsmoExT0ML90uw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
