apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:hEUjsvHAf+uZYA32pvJRtZkHKhr+/8PLMTKmoQl44bb2Y3xo76L8ew==,iv:crwjqHKT5kpdLW3QoMx3fRTX7fKa+s43q9XhDZpAV9s=,tag:asDJjY33BjFq9mP6uhCBRw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNEozeGZpTldoamtEUStz
        N0hUbkxCakd2US94STFQQWFBb3QvT0orNjFBCkR5bnhZNnRWbE5UejZ5Q095ZDZU
        Z3FJOHFpQS9CcmNzNSt1S2NrSkRja2sKLS0tIFV4OVRxeHExU0g1K1NWandIKzlq
        cFB5anlHQ3BGVjIzOG9aK3Vld1ZKWkEKYobxrmGYlqWlMNrUSmDoW0rOckUtLDN1
        ZFhyP5fQfVe5W2UNjkvUb858GXo8v9YkQXQEX6DdZ3K6Q8wPqdrMYw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T14:20:04Z"
  mac: ENC[AES256_GCM,data:m4Kn0MEDgVr9Hur9Imh17NB6FUeXUcxnsrtkzX7ppAnibow8wtCiBQz1kxvw6Z4VRP7/aFB8TbmD/MfougdHx0gWhAxi7q4MT+t/Ylz5p3KoOHe93F59SaQa/tdwSVddsycX5+UkXPRRknks58vdhaLeO8gosKhoGUpGiHNHF6U=,iv:wgFlciV0remaHXH6vDCDvyi2BGj6jeVcp+RWMoRWT7U=,tag:lgax5aJW/XHwI3LRKsSsMA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
