apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:1cD/tg4wZjlBGfPVHHL4V/d0ahoNK26BNxruNpgyQIjR8iPqHoCctA==,iv:0y/DkcaCtq1sAwCMK86N0llYc9QsTvMU9DjZ933IWo0=,tag:RRGIUYYpxMsgIQjbmgp5Aw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZXlBU0psY2VJWXVyaHQr
        WC9iNjhSVmdUZGNsOTFtZDVEVStOU0dFRG1nCmlBVFZtb2tjcWpZdUVGa2MxQWJa
        cjJnNm0yVUZFOW8yNk5FTGlqM3EzZGsKLS0tIHpQcmN2Q0lmNkpXaldRMm92U2t2
        YjVMaE8vcTNEcng1b2xteC9YM2RrRUEKIt2WqQkRq80Cn5wywHg6BqhXxQE6aXu6
        XTHw5UO0QUiaTavyrm//EKyndnf1Iz42+12zOrOn2b/D94nyofDegg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-10T16:42:47Z"
  mac: ENC[AES256_GCM,data:PjC1WXKub26TBjesTsDeOQ4nQVNhY/gLwpJxJ0lZfv3DfadmbSQ0e3wq+ozZpj5p3jO+xuSaWYeQtwbJ7YSDbm0Syv0+Qn05dK1DQayaVReU5e+lrdpSb5vVUqh2nDMJ4iuaQfHZQujkrT7rzBUPU2RbbWkp6aWwt1OVN0PdNvM=,iv:mC+pZqO3X8hC48i0HrPFGZj/9qr7Iponv+hFMlYpbpE=,tag:acx8rWer4E/JCDC/BChc+w==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
