apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:jOqKRL9wQJ/pHoGEmsc/NDFadTp0A7pCL7oirSpT7b2fZX/ZjPPopQ==,iv:GbPprnQeDPnhiiRoIEVC9RJMaiBfKpaV2tBve1ohq80=,tag:hXHKLSpmhHBkgmvyVyGCWw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQWRhc2FKOHc1MitkS1JC
        cDZJaTJNVG5ScEIwV3JkTDBzUDR3SEMxSkFzCk1yVFdyajNjeDNiV2N0Y2JJRG5O
        bXdEaTJTQWVlZ1lxcmJUOW1MRUg2Z2cKLS0tIEU2VDlPbFVrWHAzdEk0dC95amov
        VTFvMVVKaWdFQzVtcmJ6WWFVQjR5VUUK7EP6EV0oUYyOn2hjgZ7lNzxdhRLbD7gq
        8gunzY8DLEURBpBg8tq61tcvRojffFDBnwSaSvI2LfrX7+b2bKPtUA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-29T19:43:52Z"
  mac: ENC[AES256_GCM,data:PpX+WMj4alaGUA7pgv6cvIwMr9szM8FtFXAizQTyeV0HW9/Yl32UC/dXlPB0MUPnIvAyNpyG5j3IeOvKoCfxr6Q5RzOh5gMPlykaGkGJWpN8915qMgxgJqto5tPlY6PMfPRoXrw6OY+UvJKrx1XkPk7QDz96kiVWmBC3+1ID21c=,iv:wFWMHoZOiKyGVew4pXbwneExPHpBOYw8GwbH89b3Su0=,tag:jIMgzrCcBZwH2T6mH+9GkQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
