# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:m8Nx1O+uRHBlT3m9,iv:zsA6rqFsJYCihh8cACeeygtjP6XONbQBs6Ftuw8sv10=,tag:+CVyVeBzrTi5t2ADfJJl8A==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:8s7bheJCSPekr2PKiZD4Rz16BWLYN+QiCjg0Mg==,iv:kdHp6s26G5w0t8Qug375nSif/oJJj9G9yiAm96U64TU=,tag:9v74KBAF+M6sqnYT+fd0sw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MWsxWW51czF6UVBaTFRz
        WHJjWEt4b3hjRnlsY1EwK2tEcmx2WE1zZDNvCmVWVTMwKzZ5Z0VUY1hhdXhkUTBu
        UWtmNmFIc0hQd1NOS1JCRy8vL28wejQKLS0tIGlXYVkwcVFROHcxUHEzWndqMFgw
        UFVUcVc5NlF5cDkwenVnR29lUlRnZXMK7BEFdo4p+eMWOYdrrtOMnoU50qpJIKYM
        AUaJuLo4zsq4ozzZJWqJWzv9SyZtq4JBPZ6j4lEdy2EFfQw0zhPlDQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-15T14:45:31Z"
  mac: ENC[AES256_GCM,data:4ARZOnEnS2b2I1BlTi85Y7T87HQBSd8Y5BOWwIGBha+su5pCe+5A7yJpY3Byj0Yoc2YUrM0eYDRPl3/3r3t3t6qyRDxva4ksP6+7nxClbna85dlh5tKETNxUjq65xvk3B13hfrRyAGiez6oVta5HqoGVohFS2RR8MZcbouFvNlI=,iv:IWz+CIWrZmMqI859JKCwXLn3iwpZP0vLl6RQdVUKYdM=,tag:Yy4tiz6JgCPVTcjtO4lNaw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
