# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:0T3B8gaPSdR3MY3w,iv:+JiDw0PjEELnD3l0qKoLlDeS0AlRc6nFKzaVPS+YIWQ=,tag:Ixks6vSOA02pKkZyWsYqpw==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:/LZJX5KhUhucehAUhhMkjmK4ws4zENFT31jBTQ==,iv:GvCOah8jCkuxtLCIfn3gFfNtITpta1fBfsBMkt8BkwY=,tag:jk2jRWsrhIWT/yO2CIjzMw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZ2VKOS9yWDM5MllqVTN3
        QXZpVHYzb1ZjUzlnRUxGMit0Ykg2KytwL1cwCkNoWVdCS09wY0ZBWHRWTDEyYzhn
        anM4ZXN6eDNHd09ZcDR6SnRMd1VWWncKLS0tIDFlZmJZTWtMVytvbC9tN2xNclhO
        YWczMGFXc3h3Yy9pKzRjL2hvYWNCbncKbaF0Q0taeB3VWUYxVNdz49RSgaIKa4Nl
        /b2Rc7/+WW5qLJqaUkoydELjS6h/u7RcvUjakjWjWnLaZk345484YQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-10T07:29:58Z"
  mac: ENC[AES256_GCM,data:uKQuzp9TCQ1UJStrc+HicEL/b6CfmJKVku6PdGqxmfLNCdPWQsTQXFNtIDKjJYINmcO5lBD869BBHLm3CCq8TQ+wA/Jzxv2BtlV2TEMdDUmKAAXVkJD8KDYf7U7R7EwUVssHPZnaPycmpSejCOlj6/cxms9VcMN35cVzNjtziBw=,iv:NEIBErL9Kge5FDGRSd961fa+L6/txNSxoBkySD2eg8g=,tag:wlKNMC1GUXRfkcnjqFHxVg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
