---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:jK3ARIzRYQFSKAfh,iv:kQ0EptuxiPMw9krvsEoULZiEsZytQJP2IQgcBNv2PaE=,tag:Zopom59PZQNtfz0Ey7Ew/Q==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:l9J0IoGMWLGQTlvQCTs91GdG10so6NA6z9v/uA==,iv:y7SBdhnbY6PgbOBhUVP+uOesEGQMB/lmqzrO4U1Myno=,tag:ih/ZeDazcjX1NCzYasL63w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cVhEb1k2aWFTNXZYZUpx
        S1AxM0tvVk0rQ0F4SXlpdXJHMG9lK1RDNHhZCjg0dTlZTEprVDNYWm5tT0s5VGFj
        SVZzcFI5Y2dQNHJoTFAzSnJxaUxZZjgKLS0tIGxUVDg4THJxRGdhTERZWEN5aFk2
        cHV0aGIyMm9VMXNjaGs5SGhFUEQ2YmcK2Hzg7x6+FPuRHhKS9e3tWh8AdkvI71As
        ctzxhv+FBTGFxZG4Be03W7s1GuKVf4rP9CkE5XaJixwivYWEMUiiOA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-15T14:30:52Z"
  mac: ENC[AES256_GCM,data:xUcrWl1lls2f7i+Hf/8jHGczBweXjMkH2kIZvOJpyJ9dCbGGqerTNb8209sB+kQoWJRnuvXE3ZzUjf1wf9QRdB4gJWPxg68aeAp9maJgrkFBolJCddCf+xIT+qXoFDsObUS+LBRqe8Op3FcHESy5I5pHFckvee/3JP7YAogrOUo=,iv:Bx1kTmVYt7QsdXnHYaJKu+SmbwbpHPdOaImIWWjw44A=,tag:dQH2Aq9wH3Ui2jpo5wOzNg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
