apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:OJzu81jYcpqi5XAbjCE=,iv:1Q/ySob6fjOQV7QNKYTLpiiSwHVPOURPv+rVSGU4cjM=,tag:htn94XUD0hsr88jag6/G4A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1S1lXajZ6bXFqcTROZkVU
        SWJCUkx4c0U1ODc0emxtbjF4YXZYN3BRY0c0Ci9Gb0JBSU41NExYaHJCNCtrREto
        NC9kTkZTLy9qaFF2cWlFcmcvYXBIcFEKLS0tIFp2OEVxVDk0dlU4WERqVk9GdUpV
        ampuVnFWbHBVN3pCSWZpNGg0SkloTVkKRnaITCGQbuKF+FQXLIe9P5C/5ibsGjDB
        dw8VUYKwj3LAHb8mqoWP1ZS8TV55vCUMqCSfBMz9W+mbhif2jdrEJA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-12T16:03:11Z"
  mac: ENC[AES256_GCM,data:YYFIssqO2LWdryCFTSAwRwCHSwCjF2iJESBUDnFDzQiwuPP6OqCeaYSyaB6Z/M/tf+lBZ1xzikM9oO2/tmV3oWiciZJDy4epa27DXm6L+VUXnoxCtyMnlxyV2qrRX/GU98upLrjSQA52ouq6exKmR826cevkEUM7yf232cgXPsA=,iv:D0zEHiNVfCfAlQV061CnQtXGPl/mWeziru25g/v1CeI=,tag:BQdZEqzOltyBlFeFCGMJog==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
