apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Djrw9M1Ccq/M5+mmSiQ=,iv:eSjWVqNkSQqoeM7m2qWDQVKgK4ZxqwTdGS3ddpIjHdI=,tag:tdtYLPy/FkprPHPGXWxNvg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzK2hlTGdhYmdwZ3BvcXB5
        enM4aEZ6NVN0NGIyMk4yMVJuUlh1eFgrVkY4ClVnUi9RT1lORnFvMy9GUUgxd2No
        QjY1ZEwrVjVqcTVKTTdiWUtIZEdRbG8KLS0tIDVGdUVKQzZlMC8xM2ZhQm03UTdl
        REhHaVNZdk02M3cvNk53VTM0UjROYUUKUaEcsMRC4VE3zPRQuhnZOeBJv12D61vK
        k+fmoqNHF6BdnKu/ucopgNub6CeM2WLHh8MFYtCNGhkHvyhRNBcGqA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-11T17:15:47Z"
  mac: ENC[AES256_GCM,data:F/e53mO3t14rWkRQm6NsJ8z2oa1f3LRIJ2xFXU7HoFZ+ED3uXrw8xG4b4HOeUIW5Zvv1kra1vnd4d9IJ3YfEbUe2JW5BmQa1tCAqX7d4qZA8nykyrkN9zfBa+ME+wtEafPXIFH058ubh2un+5/fHp2XBMUtfFThLGESo5H/IX8A=,iv:TCeyV4FsSKR7FdiyfqNNRrv/d9rcBUIUFA54PDfsSFs=,tag:+6O5Lt8jViHsq0q0GDXMHQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
