apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:AWvalCChXAyC25GQ5eg=,iv:XlAqyQUynWTWcZ2qwYCa9kEEQ8mKAknhbjfIzqnTHyQ=,tag:pbMpC7AG+cBO64306zImgw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKL2l1aVBVRTRqcDNTNC80
        UHV2WGVGMlY5bkVqdlBTQXVGTHA1MGJvTEdZCnE2OGFZNmxIRnBVakpxajczbU9G
        NFVFaFpXOWdzRVhVMm90Yks1TkpUZHMKLS0tIDNlcnpFVWZiZUdvenNQNTdvYVd6
        YVZXTmlnVWVqcllJOGpsSFhBNzVEUE0K4DPNCDHwlS/9jsHHxVHUSvnvBXarIYMt
        Xfldg+JbCXktpECXJ+i0fII6HNVIVk6XiD6vH0nMTjZ/O9sUj+mPNw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-10T16:42:47Z"
  mac: ENC[AES256_GCM,data:NV331rRxhsPRw1MYpD5S1i35qT5VEaCBKh0NItCg+AhoNmeFRPmCLM20OZRlKtSRZECrrxpnreANZSktm85SS2ChNsLHkSl5cMHHpNxbiIp1ZEs69oYl2NrnAW1lhha6zcsCkA9vKeo6yeYX4LQR8RCmEOYmo+OlN7Cl466KorQ=,iv:ggnsP8tg4uNy9D0dTYc5xaB5jAB0TKy5lrjvR6Zx5uY=,tag:dSdpq8+PL0L457fuURB/Aw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
