apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:xv5jPY1C/sDX8WOUt7nkGMCC8KxEXg1UTowffv1UwCM=,iv:HR4JKDbWK2M/ZApBhBEjiUQrt7xaGZDtXhrtFCTYhyc=,tag:N6Ltawwrq5Wtc54LVci2Sg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcjJUd3ptRkJOaTVDN3hD
        T0lOczA0TTZjdWlxYWYzbEVYTkhmMjlaaVZFCnF5NzZXb0J0bG9LVjhrYVFsdUk4
        dUhuNHNpd2Z5U2wwcW9MbUVaNEF5Z1kKLS0tIGo3YSthY05rSW1hK3NoeHhjcy93
        UE8yTVBKTDZsYTBPcWlKdkxQVzV2dUkKYI3YvO1mOQNyyU4gWdxY/Mxeh/bpBSpM
        DL3R5W+6ysPUKXhJZYI4OtDdkKuIAOpqSfRcoTt5ujKFxpa6XfhwLw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-15T14:45:31Z"
  mac: ENC[AES256_GCM,data:6xm5OiNoultATD8Fmgun0K2LZ+opR+I2DikUzUJj98RcFE07rp8P2iSrHqfRr8Va7k5Kw0ncX69f86qrgXs+rfxps2XxzwPBK4mfS3axM6BEjvUc4eSMFjroI/OIZvwg5yaz21um0Snrntb87B5o5G6fviWK2TCl1WP3tIFdz4E=,iv:tWY/kb200JBbFlAkG5+jPmFy5ne4FMHm+aPJiTX7hIQ=,tag:D3Ajqpv5yvl/jBfs/+QErA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
