apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:8jAlo5oz8pb3byGo3VdYzgd4KJ68oXz0lKDxjlr/jBU=,iv:X1yYeTxI6AsVf0RDftyQiPRBOSEu7yls+oiKReIhdzA=,tag:RoH1xX5w/0ipmpGKFNUr7Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbDNQbmhQZUdobTF3VFFs
        dmlTVURYK0FwYUZSTVExa0NuaG5TQ0x5ZlRzCm11dFhkK1loKzM0clFLTXRxcW0r
        ZUxhK2JjNFhUYkliWTVaekdPMmJQTzAKLS0tIC9kWXViSW91TU1hKzdxazIrOThr
        SXpESUZxcCtid204cXJwdjNzU3hRb1EKvQao2Xr3F0Wa4Qhiu9aHZrBacX+bRaR9
        n8ZfjktKxLbJetN/qByAunozEJPgjxXCy+7dlslUmHfUbDMoVMY3Jg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T14:20:04Z"
  mac: ENC[AES256_GCM,data:S6YFNlTexbdCX+1cGhy3o8PD/3XDgN2M7QkKeZhbfA4Xa/ZElVabp1AdhBf8YGR7o/QxjzFQQf24aIHFd0Zx+hRdg9FsOuc+sAi/UZg1hOGEyc9UxvMXgfwhTuKEkWeiT0HFQvwpbF55WJv38j0haDfrIuYYTBor8iKyIihka2k=,iv:13l+8gI60PN+YdSHjyZzka+6ROzTYRdZkHE5WEsync0=,tag:ckE4UxUUktlNqqs/K69Rlg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
