apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:pDWjXPjrQ1qV3ATp1HYSGz5CMNHvsZifZvqftHiHpps=,iv:YvDqfr9P/Wf/fGqg1cG43A3ko5qEF6NDvK3XGQclw6o=,tag:QaqB0sK9CSO7vPv4sK+uFQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0U1pkdGsvZGM1RElDd1dk
        Um1sV1pnaFNNWUV0RmJPOHpSRFlmZ1ZpZGprCmE0ekRMSkdQdUJhb1Z1dk1CVitD
        ZE1tcGRCMFd0eHJrUVJFZUVKVUI3VTgKLS0tIDMvQTl1cUlmcklzUnhicXhNYU5a
        L1BGaG1tUWZuQTJVeDFrUHFZalgwV2sK21OG1fW3wsb1bP64ilnRqWnsyVgei4g5
        2OQTtvUVvyadsUnA/1WuBu+53nQgVefQsIGdqMbVaq89EOUXwyp9YQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-19T03:45:39Z"
  mac: ENC[AES256_GCM,data:qO6vkIUbF5iLAozT47dMkNCLV+hZJ07BYZBdJyHIu5r8MrKMHYjJvRbHtGuYe0f84r8YTgUiX7udwkeT8ylvVSd6zWpCsHbH8oTmrKTYYFTero0+ieT60dBa+WjcnE3UguvkHXRV+9q37t/IhgjZHhfY0nDfcQTwCs9z8Z/CIgc=,iv:zPY/Ypu5dlEIVJi4rlll8/ysly0HuEWWzzg0egCV+5Q=,tag:1wPuz+MDn45RFkjP4mtMZg==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
