# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:0VNYOGdyewGQ/RFe,iv:Df5TkXNrEMGVQrLaFu3NmWqAKP4uFn5tcHlLETyxhxg=,tag:VcaB4eYoyDgvmvhIZJ24+Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYlk2aUI3M2lXMFVHKzIw
        MGl1MEt2UVE5RW4yTW1FVExybWVPU3VsVkNNCnlRMXhNdFl5b0hqUmFQbWJUSkRP
        ZE9CT050WWc3N2dkZDBKUTk1NGVhOG8KLS0tIEp2SThMNkViUmM2YWl2eC9tNUJa
        eFRVVkJNNTRIeWZUeDM5aUxlTHRmYU0KnoUdt9NwHE2s0r8Sfq+SWnb8PYlRwM6A
        FIuX3yfRvwfR5uLodlmFlm46R4QPBiEW54q1JPPVWygM0D1RRACFsg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-10T07:29:58Z"
  mac: ENC[AES256_GCM,data:FDTo8NKkqlAf2NDRdNlOCzI8x93wLk+iSVG6paRDohSxfLFZJwdke1XohDaBwBBPjeUsqGT0vel66kJiB9OcHcuxx7ASCGKlVlzQbqZ0nUKKFkq3zjF8/duEDSmleAlEsIB8DjsbwJiSfunitw3rwzk4XDcIZ2p7QWIMAnDdV2A=,iv:XThU4XtvU0sg4GY1WWBW6f+yT5bAQKxQGEzXo2XbTIg=,tag:J3aSORdOiYgRCzSpfP/IDQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
