# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:tsKjJSGK7I/NpJ0y,iv:AouXAS099NV1xA8Z9e9vVFn6j92nJp27J1qODxFS76w=,tag:xclvJRGKK0dkgH87I7w98g==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RTU2Y3JkdVRvTkQ1dGl0
        c29SckNwVHArOEF4OFdBNXczVWJKZlp6NVVRCmVsT1FzSUVDTEZmbUFPeSswM0dx
        WE5zaFNvRTVjQ09kOFFKN2dOWkoxU1EKLS0tIHRMSlcwQ3Z4bjJuditCaU5aZUNu
        WnF6eTJoenZoMzZVb2NreVMwNVQxOEkKMDJWsAUZZNoLRjFN20RDPuPP3XyDUAfR
        kcvQrDRkuZw5plFgg2efRJ6sXnAGV33+heHM8JgpqWueG7swQN9BKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-29T19:43:52Z"
  mac: ENC[AES256_GCM,data:oVBVhI5mFmZfSXsIdXoeoePcleOkkQ6rt94DoR6V4GecTVGMUray23pUl8Ya//rofvIoSWFWr4TZV6oOT66VUYzV+rylrus0fm9TiRGvssMuzbYzMiwG+aRChS7V5gHjhxfiBRVeYOahj/jSVi4Z6/3vxoMu+5ERupUhqC4CvTs=,iv:IAznnTibkVcCajkCUYicwkcMg/cw5zd+FeW5MZ3LyQM=,tag:S2/dzvQcMZkzBLSIzEDBSg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
