# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:NnO/TvAHThrQTmj0,iv:BmW9nBMVH2QxSGJa+1RvOFUWbRSfTv6op2ATWaOnhWc=,tag:q/XzxnIdfCJr1oQkoUdZcg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCc01wWnhSaTJnNHNCTzRk
        TG9tSTF1NEplZisycklaSWpzNFJXdy9aTFJZCjdManU0bTVpL1E3SlNhdENFZ1Bz
        SWYxTFJkMnVqSDg3aE9QTGtnWXQ0RmMKLS0tIFJZbFN1YU0wOTJJZEtDK1ZCeUNE
        OVF3THlXVlVXdGx0QnV4Y1NwSExiZGcKzDTF8ES+yAKtQuopqJw2JMmYftyMqJ2u
        L6oQOUW2lYPh9MAEvGJcQWxFOX6ok1Dp3dmohBi2AwbLb7ieuw+/0Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-15T14:45:31Z"
  mac: ENC[AES256_GCM,data:jwGJtNtEvyg3YM7OrVnPn1411GDBQgSpOB4FYDqXjHnCWUGy9COY2rA87aebf6VnYqyKOjF+LCA64Nvnvq+bRG3O0mGcuHJQMY0Djq1w67GMUWIFk0pOCt5FPMCg91jXTretPtdZPXLz8N/D2SM7JwgjCB/U/1DQL9b2ZXV/mps=,iv:obFiJUA3pCmqIyp4aWFAcJjnCvWwWYXYVIvSBlRqvYM=,tag:lceLat4tWHIp1Ux3N4A3lQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
