---
apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: interceptor-route
spec:
  target:
    service: stirling-pdf
    port: 8080
  rules:
    - hosts:
        - pdftools.harissaeed.com
  scalingMetric:
    concurrency:
      targetValue: 100

