apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: stirling-pdf-scaler
spec:
  scaleTargetRef:
    name: stirling-pdf
  minReplicaCount: 0
  maxReplicaCount: 2
  cooldownPeriod: 30
  triggers:
    - type: external-push
      metadata:
        scalerAddress: keda-add-ons-http-external-scaler.keda:9090
        interceptorRoute: stirling-pdf-interceptor-route
