apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: stirling-pdf
spec:
  scaleTargetRef:
    name: stirling-pdf
  minReplicaCount: 0
  maxReplicaCount: 4
  cooldownPeriod: 30
  triggers:
    - type: external-push
      metadata:
        scalerAddress: keda-add-ons-http-external-scaler.observability:9090
        interceptorRoute: interceptor-route
