apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Tv4rE1RbhLNSYiyNbTtG81QerFO7bXIeokJp3mH1jWYjwi/kJG5Oh0Xzj15JGwHWd7qzXkltVwUne4MKqWn8bYghzaacPs/issy3A6KDH0fDuc4K0LHzjyDIuOJ/DHcR9oA+nSxCSsYv0cJjto+eOFRLyL+7rrGIASX+yv1bCqQfhmdQKo7+AUeSd3iL0mjK2Irsg8kqoBhXaW66LfVyxW4weCnXgePBIqsVnShJKJY3ixWa,iv:M86bLi8W1T/zjWzRur83m8jiUgqxc1p+osj0qWg3qts=,tag:W7taEz1m2aWEd6yvwkHs6A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOHJHMllVRFJNQXIrdHR2
        d1NWZ2c5ejVIdXlBT3djKysvcFdSYkJObGdJCld0ZTY5ZUxqdXU5eWF6YWR3cDRQ
        dlBvc0xnR2pyZXd4YkRWWE1JUkFySEUKLS0tIDRoWTlKSE5aK1pZWlErR2ZWclVJ
        ZjBCdHVwVGhVSU5pcEFqTVBnWEN5OGsKRJfm42T4WZbyz46Ml5tjw4e1oRhpdd9u
        u6sB0fDYHu4klbdIf9q0/O9yG49NVosYohgjt4q9PELSsGmJYY/3+w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-10T07:29:58Z"
  mac: ENC[AES256_GCM,data:8+QcJaiax3ae3J96hkd4pSnL0Ui8Pr2KuUk5p3f42+EJSbZg1m5dRYh/0LJ5bij0jzgGD7CtPud3NzdGsBfBhqVqmTJdT7Ss3MJCud3tdeoO/7WJGokMSHdDscIOV/caslZ7gnahpBWR91BV3sZTBkOJgnbrVpu2/r+INGwVJ44=,iv:eU1wxeMVaOfQB/upwLlpzf4q8u0nPff9FNNi64bBkIA=,tag:tSwh4PYptaVOAE8TUKj+5Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
