apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:FUEXw8E81Pmg87vSn+++4zbNjfg6xlxY2OBrJi/bkgJN3yp9y1yIbxAOOpAcT41UTyezaQUYHidjQIj0b+9VbLnIWoTNuJX577iqeS5OiyA25CS5pBSJoiq96cUirCTkLNefBqXKZowOUocfl3pt+Z2afkOfjttGUjJauD8hgn4GkIgBlN1YgGo9AKNXzst6BePOedZnYt8WxxJXb0qFIswufL9bLq54RqeDD5SGJfplbwGM,iv:HPOSdXxa+45o5A8jkzCkSHdg8cSA7NH6IqXch+OglqI=,tag:LVpp3Y+uUnVv2An/BoKpBA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJK0o3S2VWUzVKQm5xZ21E
        MmpuMHNHZC9JV2Z4WmsrYmNkRUQ1MkFCT1Y0CjlUSnY2cTlJYVJRVWcrMytvS2tH
        b201YmJNdzQ2Rmt5cHdLQnZVTWRkaVUKLS0tIGloRUxjRlk3cE9nRUg4SldNdUJp
        OXdJdnJsMllSdXFMQUlDYk9YMHIxZG8KVkIlRIe/bgigjnFM0V8qPadeaoemoWu3
        vxECqrfcniruNAK2EtLj0tPp03Dcoqmb4LwbPDeXwNANzjkoEUu60Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-19T11:25:39Z"
  mac: ENC[AES256_GCM,data:kHESV3OOxySIVGlLdU++4gZi3o7f7Kn14zis4kvh4/WIlzPcXsz+Vd7ohDDTRwl/bVU/Ldk0HchClK8pV8rAodeP18V/8WsVnOEkNq4cw7b3mCFYnzmK/y/XVau+n0dJAJXZsUzUVMQZg+BkiA6GgjOPYe3qgiReOZRpMADgcjM=,iv:vyrSQgUg6aoOP7GyocdXwSE9NfkVXmZ/LVSROkXS+Ig=,tag:/iQfw+LBLk9gipPgV+4i/g==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
