apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:uX+QE9R9ocri5cwYXqmoU1Vn9JsnbjgTRrYporVxnd6u2gYo2oSR3ZTFQi5jPlgjZJ7DgwYoXPlgqTZwLNYn5wE5boQOzxbc8hj/TjIuY1y/OZn4jIONhBF3Sfn7KRz5JCMf5IC9184rLjsPPBNBPMn8poQQOfkGQKOyHVHodSwz/gcPBiqJBjJjHzNT2m3V5n9i2lRVVdAgOrZQxKAqhJaEga+oKqbYEiieD4hwb1rNlZOA,iv:rCZRBoRxbF5UthULHo5Vs89AxZizW6WT5bX9jGu1WoU=,tag:euGqpcRORnNR8qBKnOxmOg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMDdPREdsc2o4RHQ2ZGZT
        ZzZjcitGamJZVjlLM0lDVHBLaEhxWnZKajE0CnNOaFBEU1lZcXZoa2E5S3dTMDdR
        SUZ1S09MU0RhbGx5eVZKWHhNcFlTU3cKLS0tIGZuZFRMZWk2STFZK3RaakkxS2Mr
        L1pKUW5mODR2L2xLMUMzWVJnVEtuOVUKbKUHUe9a8F/Wj6KmzvIVzEt8m10DEuz3
        hV6/Vr07JRaTihbms49n95c4lzCfhrbvpw4AOxsTBbk44ULr7d5Iaw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-11T17:15:47Z"
  mac: ENC[AES256_GCM,data:cWzaQFmm65PB0mLtQEFSNGxIeX+t0DFazbUVDC70HIZVMlYbDP+Fzaj0REJ3+w6Pv/13O7N5zFtYDNPehPE6T6zk4nX+c3OYKnwz0miG+HMbrj2c7CKdhgLfqOzlHmEShFIXjoxtVHSGlge22p39I0qzIikSP7bznpr/Cz/jGR4=,iv:nzhvZSAcSYJkfzzk9NFpqj/bRkWrmfsdEIUgXvB3iJU=,tag:e2VZi2GNi9D97JHX5OkHlw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
