# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:ZAdt5sM=,iv:mgeOdJHg5Ron2I21iUMRLQ4ghxo/g/fL/2Gswb0tZOo=,tag:50TrQYcXu8fbyfhzNTuZBg==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:bnxgZ9SLpXRWbpPlI/u2KcSdvWskxqs=,iv:eXvIZkbuieIJbdCOoL7z4M2ZIP4yBwVgBgI4vyiVv24=,tag:ylKxDV4/+m789hPffRABGw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpV05qN21TZFpnaUlGUXNT
        K3VGTklrMkZ3Y3ltTks4aElBaHF4ZTFJNVFFCmM0bXJpNzRMTkNWaGUveFBRWmFk
        NjJCUXRrWVVFQ0Z0Z0JDMnVPc0RyZm8KLS0tIEx5VUhqc0c0Z2lObUt3Z2d6eWFx
        MjVESHB6YVhRc2RtWGRrUlNnYzBHdzAKPZIJheRYcRI6fLlpWKzU+4xXVdKvWJ7D
        0GeignM8hx78nHp2GgtDW25Xgkp+iM0FO9PNHlod19jngmrER8GXtw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-11T17:15:46Z"
  mac: ENC[AES256_GCM,data:aWyGZw6XYyj6gXjcQ7YmZk319kfqnEqlbP9gtp2237aQHqYbQFuaLiR3UZWJvLegAn6FGgIW0y0bER0gQ18j31ywGKu4j6rSfRRL5KhUr35MaR8qLR/4BwFL4t2Z8MycCAuaQ6CZ4+X7oejHqX6WXmN1WGiNoWkC6t4mD2x8JMU=,iv:7EMyMNR0QSSXn4CMcuugjY3NGYOa5zpYBNaqxvEjMf4=,tag:FWrUpxd0PrvzCAVOazNFKg==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
