# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:E7Rn/UE=,iv:kPwojSUGmia5X5yRAh7g+pnpTuHsgOENps65L8JiU8w=,tag:73N42svFio0fiaYIO2oPRw==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:0rm0KnTgFzJL5iuXmN6vQ/VG6dbcp9U=,iv:gekbTdpQP5Ony8aPh5d8rzfQJKD+lAj7buAX3nu/yo8=,tag:yNQZsbJ6l26rB5IeNjRakw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHOXNmZHI2dko5VU1BckZE
        cVRWcmJPRjdKYkVsTXBqcEt4VnBmNDdmdzBzCnRHbjVHRVlTZSthNjUwL3VXcW0y
        NmVrOHlYTThTaVpWQ0pFQUlueE9rOXcKLS0tIHNxTkFxUVUvaUNLOUZNTWRqclN3
        VElWMnpPNUNVT1FoSi9hYjU1dm5HakEKYRm1jP3+FouGYAAC1DJD8wcsaRF4SOxu
        UAeLygh1jzSR+xCN3MbaAYtCqM4CYRe7aoxkN0d3z7h18HYA+Bb+7g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-25T12:10:13Z"
  mac: ENC[AES256_GCM,data:XT7vfBOJd7CSMqAhcZx3ZBIy9Hk7yorkVJZ2iLPQBuHGkhmxrCg++KzszvAIRLNOPEB6CJ/+dZhg9JsqEbxdoOvhwm9qJQvNtc5B3F2Z9CwbMbmg1sp596z9FhLCWRpPWsNsL5JmJxpGjbUP0ja43uOZhSx6tzGnhLwuBgPdRF0=,iv:ECkuqSFFFuJt/1QTDNiSdomlx2k2J+7eNcLFKl62D0s=,tag:/bpjF3TPuvKe/t4hJeLmFg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
