---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:bjCNcNY=,iv:YAAu/vaDyQM4VWvqcyGbUJfTnCOdw88FBqCVkLb9bKY=,tag:DyjSvNJSusZJxPtJ4ZU+rQ==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:+MuVh+OcCu2QfFFWbhztYkOn2nvFS1s=,iv:hcfL64Q++pCKAY073xW3+Xk10KCaO4v3x9U8W1el97s=,tag:0jPIfR4jOl3DPPCtTL3EBg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbVYzTlI0clBYOWVnYUUy
        ZzUxZ0RMUnZ4Ykc3dGN1a1UyREJJaXZBNGdvCmNYMDJLUEZRSEdMMnI2UXUxS0VL
        a1ZUK3lkU3BBTmU3YmZnck40bHlBQzAKLS0tIEdsMGNDMkxKR05ZaVhmbVUvMW1k
        a3Nsd3F5VmdLYktLQVdRcjdBb1F6TlkK6czfDNzNwBJiagTmiLacG7r7+bJITDos
        LoPwDqoGb7c7amRb+vguDaR09oBEsYvAKCvcq147qTPUja01zvyhZg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-15T14:30:52Z"
  mac: ENC[AES256_GCM,data:PpUyV9gHvpWkaziJdjCPJ25wrgDix/XR0YPDRANPeBVsVo3P5JsZQrlB/szVFGnFNeNx9fRqTq/ZfCaewyDq7eU0JN0RN8IhsztYRFeI8jInqYW4R78AMUDnnfALS1m6Qvpiz/mvTfI5zv+sf4FnpBhBwsMduqGQhBA7+vGBSnU=,iv:cfa41wAzspibJuHJk96bws3rsWA/XiXtn+mYYv56TXU=,tag:Tb8g3xu6R3k3CBiVNmWeyw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
