apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:NY19BaFNloQONinJ6MmdTOPjvmOdDImJpvrFImQf8gsC5O1FzF+gKA==,iv:o3IRVREHlk9CWBwOyP54kYnp9ZXY4mpsmHED23o66g4=,tag:vojDv7ucEJUsZ2oOqnzd7g==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacUpiN0RnSkpLcVRzSyth
        N2E1MXArU0Z5V1RsVnpSdnNTR3F0a2ROU0JZClZuaGt5cVpYZm1nZUxiZVZpWEZR
        dWVWNWEvVFhmNlBJVnRLVmk5NGFveTQKLS0tIFNBeXVRQndVemQ4aE1XTW56Y2Jp
        RGM2OXNRa3BqNGN6TWc2eDdwbE91ckEKiQgsTM+YVqkfaB0H9mjKBhQe6WhieDH8
        RD04sIzXTwYHZ3dZ9IX6nlqqfVVQnckUVCg6UbvCdBp9KDPmY1Mq+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-15T04:37:46Z"
  mac: ENC[AES256_GCM,data:niJeG8Wp2QpcDetPiEng0Rw7p+ZgcoVxJHNmKWokLURBZg0/xIyLAmkc3oINI1xEJpJdR0QrxHNpIr5ZGHTOIVSaiBYHTIeJSBKuyKyWdUR2OyAeusyGQF6zOtYq/tCWoO48kSMMDNDP6re8+0FnozjNoNexhLLeNktPEKGNwNM=,iv:ba3jpEWJ3K5t8yDODomSNk3V7pB2fUGaMwPVkF2GCdk=,tag:ooKX/RQRwUhJu9QJMYWxRA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
