---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Fh+Yz71QOWPOvLvWe2AbhOwqW1qJZrpL48FXI/FIOAbAkC0zrAfQaA==,iv:fNgaamumw7+vrxRPZSml8BbxhU3SRynyWD28xE3QcvQ=,tag:QbsbTfWC/PALpA/XBYLPMg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUytRZWhmUTV5Mkc1d2o5
        OU9tV1VvWVhKVW0ybE1SQmNMalFlRXVVWDA4ClA2RElWbHlkNE9ucVVJc1ZRK1l3
        cDV2cGMyOVRUWHZvMnZUc3BMdzA2NlkKLS0tIDcrMWo1KzRTclBzQS9vbDAxYlJI
        dGFBZ2wwQzhRcVVORUw4UkJhQXVsNDgKwngpW6/OXbPX8bSVA1NugUfSzA40TXMh
        Qd/XYRNlJ7PRtr5XJ7IslfTa2SjPeyh1/XVjOq4+a42ap4W4GoP+1A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-15T14:30:51Z"
  mac: ENC[AES256_GCM,data:AI8OIO5LMRVcdvvY0RS7ONvI7FoPXss1aDkbq+or1ur90f8UOxKntLwo+EMxysQ6MYiN93hpB2VlrH0v77xt9Lsxcw/FKOxd4f+XJvcL9D6WsOOrr+noeGp58Ooudks9Vg7sNprlGTzvlB2CV4/c33HK8/8gRNBRdZytDhKmpfo=,iv:pBRg4iRYZczuL7IkZRnfyHtco6QX+d2Q8e9yfDo9+fg=,tag:1seagwLt57KJgz7R4ZCLVg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
