apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:fdWzipNjmZ26aVsW5hUfX9hke3j+mQyGK6j1Hi0asooujeLFswqctg==,iv:bc6UUG38WV8c2vcrxuuwe7SYeSUkxOxmMbhaeczIUbY=,tag:4YlwzOleEkGmI7VpcGsd8A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMTFQRzFFLzhBV3Jwc1Nh
        SjNsQUVwdVNoMjllV1ZjUkFLSjVxamdVbDA4CjJnOFQralZ1eFg5NXhQdTF1S1dM
        NFFCOElRS1BhK2ZlbkdRUzNJaVd3M1EKLS0tIGlUalZ3ejZsTmM4dGpVM2lpMlBm
        L1BOS2pMMnFBVXBaaytFa2l4ZzI4blUK1gMCoK7P7em4LE8cVLdwAwjzsZPc9OfM
        a9L6ZYXRSxpKQfh6ZdAix+CHjwnY93dp0P3x1TPahKBT2RxzZatoIw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-12T16:03:10Z"
  mac: ENC[AES256_GCM,data:jitxyYaqsyYmMvCa90XfHKznkpnitRh9mtqafvT/W9FMbg2WfM3uP+VpyT18RjIinoISz/y77d9YEuu2nWGz+Edo6CWYD6jAR/6yBGqN+fCvtGyiktnTE/5csKVbs2Q3+0FF0sbehA74iqckYevDr6ftHxImtR5FKCoQL6O4ZZk=,iv:j68jf8VlGhrDspGZWRxYU6gWU8c12w+OEhodXmaV3x8=,tag:UJ4+7amXKU4uXp1uun9Bxw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
