# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:8umSDUa1l6BGOOvc,iv:m5teAtxAuY4j0xQ/GU9HIoOgvlAjv+9efpzcC9a8FaY=,tag:jPYtIDTpA3vg27E8IQ+zmw==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:qxGW427tV6MfnwFPgoGci71mmOuXanVecho40w==,iv:b/AQnTa1LqWzT7/YmPI8CgPBp3PRK9VS2dtBSER1zW0=,tag:qw3TMLhVnE3OGEReONFqgw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYUdXWHFRSXhtd2dpYlF0
        VGxvV1ZPcFpLQ0d0cHRYbms3WEpqQWU4RFNJCk1hT0hEckFmZWpuWUNtaHFOUU1y
        Yi9VY2F5NTBGL2wrRk55VzZ0bHNHc1UKLS0tIEw0ZUNsd29JM1F5UUlWb0MrUU5z
        emc1eEJGZGtaR1F4Z25NZjR3MkxOMzgKJB2vFl5gvbHTMJLH5b2DdsnAiNtZyl5N
        w32rw5R6usVXJwKveapyf0JNPWaD9KF1TyKKBURme3STJ/LZaL5JcQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-29T19:43:52Z"
  mac: ENC[AES256_GCM,data:XI20LB82ZsT5ttNFNTYWUGCfvA4gHqLYnZYsQh4wDF9xpef4ryLxqSbQu2dF1S2Wbi9+eaTN6J6tkjl1Tiwfhch0tRrpOR7GbS7PCngGbV+auHV3NT0DqQt2juvqvvaPjjbkV9ob5L8/D1XXT7oWpSgA03krtvYjfGe5es4VHBU=,iv:H9KC+Q3Rsm6TL2h7tZGivpp+psNMzY/kwjwO9dhLZd0=,tag:I/uWZBArRu3bHx12v2QzfQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
