# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:vaYBRgbEtMEKdcDO,iv:9gaQ5VjKqa5LEOFuJCVenk9/QmNicG/43+crutrJFoI=,tag:lGpKty5pXvpAB+rxY8th8A==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:PvbhqgZi6hFIHIYA4lNMzFvgCN0eOCivzC97PA==,iv:F2TZ9oVwyCHc6rRl4lfeqSnTZXIoCp2tBAxEllMGbe0=,tag:XCqAUphPUdJzXmVnxE2RcA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNnR5YTRqdDd1VGNrekJF
        aGNSa3NWcmpudzFsZHMwOGJ4azUzQWJsMGo4ClFJY2czekVYUk01dG5yanBYQi9O
        SDd2TUx4L1lwNTdTRktab2lvYTVTNlUKLS0tIDQxNFBraE9TTURpandiSThYL3Zm
        Z3lLM2ovZkRUcVQxQzJHZm9Vc1UrUlEKmx0/1P52AwQ6mReOdHr8ey3tpaTSLX1Z
        tptaIbuTf3U3o0ka4gXDqI9bEKuK7rDQYAAeIo2YiAcQCC9ZFZzvqg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-10T16:42:47Z"
  mac: ENC[AES256_GCM,data:n0+HFzCpYqa41Bb4keZPXuNcpEx1V1E8R2YG0NH19TssLAdZwBAVHhDRUSezsejfJyfwN5dVfZz8tDzLsL8BUcJy1sr0wHswrcXSrOQnu40GNEf3Z0UGF0MIW1DSSWj+WzA0Hsu1doSIa3J3htxG6bAefljToWA9YwKE3eZqWeU=,iv:BX0X9QrtAIqOBenExoodeiYpVJJM7nFUTgytoPVvGEY=,tag:H/QKis9rz0bQhpmQvQA/aA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
