---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:vko8+xmsuWP0LBAC,iv:HBX3IvFkpu3uP/A+3ELp7pKK1ooRNy9nmxAc90J7n1o=,tag:ZoaKr/L1GFAzufdZYyw/FQ==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:ajMOAymTLK/5431pQLCLOlWk82IDzwuwB5EUNQ==,iv:6FNz3vG+o3C4AOe8qy7JRwXsAUmj4a1M+foiBZLlC/g=,tag:cwql1ecTKMtqmmmRWvtZ2g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTm9mZFUwUnlXZkZJUTZt
        Y1hxZEVEWmd2VFljWnQ1cFN6bkNzNVRPRDBBCjM0dmxnUTdBQ252YnZoTUR3RWw1
        SFhad1ppaUZuN09YOTBLNXdSOUp6aEUKLS0tIFM3TkxwZFZ1cGNqc2VNa0hQRHNJ
        clZyb0RTbmFiWFJuSTdUQUVVZEYyVmMK147ckJqI7QgrlqaMAir6mH8WHDfdt4DM
        vltt+FsIRv0ukFjp9vwdb/dfOqYbhcgOFHGasd04841UjpJky9gMvg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-15T14:30:52Z"
  mac: ENC[AES256_GCM,data:gxaLjHR0vSTpZOs1GxYIdsL1xhhzcYAsFZHYkcu9WYz2pZ/WjmHv16+pofoz00k8RLMCCuAEh7mMgDBde4VucgoehWBwCZpDxYxjXrxPztVioY6MCoDRlMxqDYFg+RVoSHDyiUVBHjF33wGKQwYzW0yAzrkhpVWaEFah4MF40U0=,iv:k5CmwoDAN4euLLhvN90ni1kySDKPbaW5rM16vNF93Ko=,tag:eyjddBJP1VQKCcL9FgCUWg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
