---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.0.163:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.0.163"
additionalMachineCertSans: *sans

clusterPodNets:
  - "10.42.0.0/16"
clusterSvcNets:
  - "10.43.0.0/16"

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "alpha"
    ipAddress: "192.168.0.183"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/c3aefb078d0f12c6aaa22f46905f4abcc23786a9d01f8c526ef914a8f2065ee7
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:2c:26:80"
        dhcp: false
        addresses:
          - "192.168.0.183/24"
        routes:
          - gateway: "192.168.0.1"
            network: 0.0.0.0/0
        mtu: 1500
    patches:
      - "@./patches/alpha/machine-lables.yaml"
  - hostname: "bravo"
    ipAddress: "192.168.0.69"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/aa80cd1e7c774a95574e42fdb4a421614a0aa5bc5100fa5319247f305d4d729b
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:05:fc:31"
        dhcp: false
        addresses:
          - "192.168.0.69/24"
        routes:
          - gateway: "192.168.0.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.0.163"
  - hostname: "charlie"
    ipAddress: "192.168.0.72"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/aa80cd1e7c774a95574e42fdb4a421614a0aa5bc5100fa5319247f305d4d729b
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:9f:6b:2f"
        dhcp: false
        addresses:
          - "192.168.0.72/24"
        routes:
          - gateway: "192.168.0.1"
            network: 0.0.0.0/0
        mtu: 1500

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

