# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: garage
stringData:
  GARAGE_RPC_SECRET: ENC[AES256_GCM,data:jUXCvk6G2htYUvra+HzJzZDkMxTjx1Y4mhwmH7doOqpjNZWFmkST5dJRDuulV64mWM3vHBh7ZBidDe1QhHDiEw==,iv:AiehzwkaXzhX3xpRnJRdL1pwpyMC5w+bjeztV2xXWko=,tag:HsufEW7+DbWQyePTp1LN7g==,type:str]
  GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:cwd5fn9L1ReU1MolId92TEU96pbatkkpxbaDTLWzW5l23DJHzE2KNvGEgHm+CHRTCC1q2632r68j4kmMJPJRtQ==,iv:oGsxGO5awiz6hnevr8f9ntvqP/zdq9pQVtNkaNYHRYc=,tag:wE5lCETg+vzbbpsEx0OOBA==,type:str]
  GARAGE_METRICS_TOKEN: ENC[AES256_GCM,data:YQ38DcarFlBTsskqwQMRHk852YodNvlYnbTKATeCN2vGeUat3L9aq/1q4ctUYp//03D6hHAIL+91828AnYujDg==,iv:jrrXbqhSRN/HNQUypoHvexjWI3OHGvMjF8WmJAdRklw=,tag:/Exm5Atb6eziVdZZUcaSzw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bVExOVo1SGM1SVBKMldy
        ZlZ2RzczeEpTZ1BvNm92aUhCRTlibGE2T0c0ClREQTNrd3dVZlYrV0tpR3AvSlBK
        L0MxTWwwMW1TdzdJL0dmR0NLY3p6RTQKLS0tIENVMmZSUXFzMDl1SURhQ3JPODhC
        TkVLdlFlNHhVUDhxUjVKMnhXdmRLQkUKtZ+3NdrPlUDxEZkwHzzysA7dXhYHO2JR
        soYCvJF1AuGanc8uMOf/2n3e9DKFJSqH2/F1Tb5AeOeUWmCmNoGbjg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-02T22:25:22Z"
  mac: ENC[AES256_GCM,data:C02B30eUFcPGI0jTxRozwgI84ghLh0S+KU3IqPMK/a2nk9Ze/JG60fz3uf3Dg6ei9+eTEQ7PIwbiI1dOLvkO/NjxKtiGfmw21KdZTSX+iP+sqpIiifRYiJzIlq9gzLbVaNvjG3JiSwVBSKL15LXDnL7Awiw3P/+Bo/ywDfd3IU0=,iv:bu+hjyfO7j7Ui5LkU6J1cwhuVo4xhkWeyPAzUDXLPlA=,tag:osyZ3kjg9v8PJEJZyx3oHw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
