# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: garage
stringData:
  GARAGE_RPC_SECRET: ENC[AES256_GCM,data:aMEgmmyMhMS74BFH2+kNkYixRpsupDCtOJfoeMw4UT7kglXv0SqsCM5OLHoQTgBQVIjIShVXqDWVwOvAsSHcWw==,iv:1QTznqX9AfUcKX9cTPjikNLVk5zmG1pMRerY/5HTEOo=,tag:APizTOa6mi2kskS16gbqWA==,type:str]
  GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:S86HvjY2LtgL7p77eoy7q9J+fD7shObHFl2+9d+mTxLWpn3eff4ntjGAvZwb0irVuzOvAf5th0op5kEj3i7sfg==,iv:WQ3oWH7kNfOLg9zEoLmXGhAiyipyK0adov058ZwqzCo=,tag:OCJxvmNsGd60Uv1f9hWUlA==,type:str]
  GARAGE_METRICS_TOKEN: ENC[AES256_GCM,data:KMgm2O4cmCkqKxKBNpYxXr+dcZW/6O07+Y6p3dz25J1gPqLfx4CO2f3G05N9NAlQntOWqyooQi3cTkPMgAEWtQ==,iv:EmW9DWjbIrtRgoAuA2CgqMUV8cxcN6WHjOEIvENHE5s=,tag:giDx68rlYEIgbrl5LHlV/A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiek5QQUI5YmxpTmhGTXBJ
        S3FvY2l4Wi8va3BzZTZuN3diOU5sZ3l4akU0CmxyVDdXMk84OStYOStGNExqczM3
        bDJFeWgvRC9PZ081R3dFcWZEZlJUVm8KLS0tIGNtYnlMZ3kydklrSGZTVWp5VEpy
        WDVSalpKOWVRWTRkZ2c5cHdlT2pNNE0K4TZ6KU5rxAAk4zmIedGUa8xdcykt53Px
        ybfTt//T2xQ86fPq4/BcvXuqLYyofAODQp7CO+2mxTJV9stS46iFgQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-19T11:25:39Z"
  mac: ENC[AES256_GCM,data:FwZEFFp7YiKx/0ulGCoxSNBDh9d6l9l9rW34rYkFbvlWVNo7IRJ4l/o4rQZ86sYTlRVCnuEiFHckpl1W8SJQOvfTYECngU1VIbDm4tshOYjGtLWUmjk1/XJR6+HToDJkh1nXWfjxWCePRXK8xxagNy9JoLi47MSWicrrogfojus=,iv:RoVYkXC/vqiVJYvUMKIASx7q7UIL5k1V8+AmcoFamPY=,tag:RZ/BN4sNtHpjELGukoysXw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
