# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: garage
stringData:
  GARAGE_RPC_SECRET: ENC[AES256_GCM,data:eF47w3KCmnWHzmJaUMbIkm+ruajH4n1Nm7MGcvWqYpuSWqYcNKBF3tQfVdhdOE2/nssiVAtGyEm3q+eslvehNg==,iv:eRiQlJJoZ4oiWN2hepvBQWGqLcBzHnO4/0VAc/LSS2o=,tag:TOrJJ4S+h2DNHu03ETq1oQ==,type:str]
  GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:KJ82avakz8QVAcLpinRuYH6EbLO0c8E2+82mdDZ50lXl67u9g11ad5LQpB45Q0WNHEr96RhJaZCeH6HGWAvzvQ==,iv:yYf+4lpD2PZq3FAvPPeXY8MomdwqDEvWlQrEmraCweg=,tag:F6txanWb9kpomcmzc6RJnQ==,type:str]
  GARAGE_METRICS_TOKEN: ENC[AES256_GCM,data:ZlCVlg796BaO47IYemIDn3St8O/4jBQeHmT7dKgPKe5RbF9aGY6ovJ1UgP3k+wcTAUIV0fPLC6GJSHSP3e1Zvg==,iv:YGHW4kKOCDSVckD+lfrhR1ZVyH+AA+YLMk6fiqQy8uw=,tag:B5/a3iGtNH26uDNCBXjiaQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWHdlQ1ZLcUNOSFlCbmU1
        dWc5Q3pDai9sZm5BWWpnS25GU1hVa2RpV1hRCjBWSG8zYUZnZHpKcnREV1Q1VVF4
        OW5RSXlSQTBHQkJXSnVadzFSOHBZSWMKLS0tIEdWb3lxT2NOSHdYMkxpeEVCSk9B
        QVJzRUhrNlU3azlMYjgrVHZJZEZCcG8Kn8ilNPD7s9oCJ59H7aL0DSP9XIrNM8mT
        e6fLTJCESA/VHorX3NJRMwGLcoVLKcwRSGInAWHmuTCpat1oM8GH2Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-13T18:52:10Z"
  mac: ENC[AES256_GCM,data:GYcpYS5XqqmK0fiEPm3v66w82CpO26PuQHBshiEXtmyGfQFyBKd2Rzk0u+lruhIU1FD/qbkUvMWD/Sfdh2IZeC7Se39TUzrCDHeKV3zn3pbg8DdayUDxp10b0xTwj2f8ZU/H0pIL/4adII2ftxz9F3PGppnsf/Xd4GruhgKXYqY=,iv:PJJxD+enm7iAQ0SYAwXZ11kfE2etZ5MVpGI3OOyOEa0=,tag:x3L6fYMtdUx9ixRbGjzlWA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
