# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:zFhLPFInzQbEHKcT,iv:QM2qVxG2t4ndeHyBDj1rvi0Co2W5uf7mgczNwJQySoI=,tag:FOPwicVjqLE5e4WJu9UKlA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSG5OUVR4ekZyYVdXc2Z2
        TE1TSmRqUi9xYUJBaEVDamxwZFBSN2JTTmdrCk5Ld09iWXdPMTdySWFaeFduL0t0
        eUhyMjBoWEszdjZxalJWc3JBWGlJaWsKLS0tIE1ja3FVWUsxTStPMFdwdWZPQkxa
        NEVtOHhwZUpvNHRlZllKMkkvOXN2VzgKudCEK5dmx3DUDqinhoHBe000PjEaoN63
        /ZUOXt4FbLXyCdbDyGy45b71Tgr9mD+X04SoS6lQS3iqGZxspajsig==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-12T16:03:11Z"
  mac: ENC[AES256_GCM,data:3ptOxYbJ5TUliWk2AMZ5R7icohz9lLqIz24cu9jZZZATgtu1LP4pGyEG4yEB9qdESnUyQUqbwIR3T/3LAZOlPWd/Xw2ZN9DoF5ajFS1d5fA54+h84MicSUZszTrTcTffWraljST5BqGnPQu3/37uWHyTEO7R3Fno1CGchqOFTDk=,iv:CXxUv/2ReZjX4/uSnNlhH8gntCY8S72130BW5BYLKeA=,tag:y35uKeGNv5/coM/m9lUFZw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
