# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:LsAYTGM2KA8V78Di,iv:wPQil3uu13CvFZvh+HaYDxmlslUvxRxL9XNMJseS8Wg=,tag:ffIF0C4NxqWsmaHEJOKwAQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJM1J0cSsyS0t2ckZ6aEt5
        Y2VOcjh6TlkxcDhMalNRUHZKR1pTOVVzVW1rCmw4VENidkhjRDlkR3g1bXZ0WmZL
        eHhRRW41WG50dnRKajBuSkNIa0grb0EKLS0tIE1vUktjbUlqZW1EZ2M0dW1YQUYw
        UFBSbGhhS0xobUJkMS9BaS9oZ3c4N2sKZ5yndsVETIimEp4Rc2N8rEC3Rfk0VFpZ
        GDF+WNwe18KUZLyAZ6tyjgP7Q8NTCsK1yqBmA3zDYo8VveYSrRFsug==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-10T07:29:58Z"
  mac: ENC[AES256_GCM,data:0oxKbrMwHwU2C+0kUd5892+puqjyHYegvqLTUM1xl5nU7ZPQd/j8aVY3vXBqgkirbe2oIXO6IayNZrbXZmzX9pzY99DiAfbnBblmsOreMcHasl6U7ZrR2gpGLpuGfudG7o89j0ASFKvyoUrtTW7Kd5vzeex1dGNzrLHlwfg7T/k=,iv:x5BuujzvAWno7M8HOLrXEBAFm9e7T03oJkj9WfK3XMA=,tag:GI7wUsLWdHCn4dFvjgHiMQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
