# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:IzJLEMRDO5f6GkIk,iv:Z/Kb/mtxPH+QlMlN4XhgX/sXxDZ4idcSvGVOslvmvHM=,tag:aKm95vzGE7uasdy7BcXtVw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bkRZb0hVQTI1Z1FnNGJK
        UVpyY0hIWTh1dmZWWjdESmVFZVZvYzBka2hBCmVsU0V0VFRrcVpWY1hvQmNLV0dB
        bDAzbU9vajBrdzE4NlhxRENKd1BIazgKLS0tIFEya0RVQ3pKYXk3VmxxdDlnYUUy
        NjJpRVFaR2wyRGlqVmNUbGd5ZzFPOE0KsB3UZtJdZYUojcvW1rKA84CnlQD6GOOc
        sHP1a8GXENn13k68epw9ZYM6ibFH7jmqFDrVyU9NgZgmqSxTLlHVGg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-20T19:42:34Z"
  mac: ENC[AES256_GCM,data:v65RL6N67zW0631TRzaEFk+3U77Jg5pQwlPgJ/YzQbqi3NvW/KWYMEQxf6qpUIPTRgy/7lxhstCnWSuPhbEDdTOLLkpDJUIJVXUOg2u5P/tRUC254rvvw9XPl3NLInWl++qd6tIDX+fwcRjAziSUWvoekOMP4nUnV4XlahkIOvM=,iv:rTIbcKuT4eZTOWwOnNdoRKniGYbRsO/I0cXtb7Un9Yo=,tag:XvNP8vYIDm+rGFVh9deVxQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
