# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-operator-secret
stringData:
  client_id: ENC[AES256_GCM,data:QGoghTQxNF+DmK0AgJwcZjQ=,iv:U6wi6J241z450un1YRxW076NVsLSTYXdlpJEjbOAs0Q=,tag:JR4ryrKrPTr6uG1SH6B6LA==,type:str]
  client_secret: ENC[AES256_GCM,data:60op22P8CvdZo4pgLx3TImeDUKNq4d4CcJ5uT5+fHwYPktiZJ9KExNwjAX2LhqdnFYJc4Q7WtLPu4EljUrmTvQ==,iv:Ll38HOzrAjvv7kyjg3cMvntpSc9qYTqhjrZmrpfR/q0=,tag:CcI3CGKmJ4IdlSP6TKU5ug==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2b1BaOHM0bUNnRDFWbDJS
        QktackJNY2U1UlFUZzF2TU1wekJkT3liZW1JCkZ6dHkxbjFybFo4MnVpMUFQK3NI
        V2hQYnN0MDVqUEdpbXRrbVg3RjM1cWcKLS0tIG1neVJLNnN1MnRndG9sc1ZPNkVi
        MlZVeENKYnpiRTM0VERwaWFjZHl6V3cKXptaZDVv4zz0QHfJ8zThhkudsSMN6Yk2
        e0n6SnW7zdEOgRvM+Eq+W2rDYN1FkgV0htO0Z9CutLyeT1sgCdWPiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-02T22:25:22Z"
  mac: ENC[AES256_GCM,data:jzEdRo9MRmJVEC6WAkZRYeylu1GxPSbEKsb51D892CSYPsCLkgHjszuL3TajYiqf6N/ORLlPSRz6mQNpx9RFyzYc9S6amTw6kdurn2R7kF0KxO5bx0iYuH2sKbNGkJkx3V+fflQHC6xP3MeUBBuie8d6Q62avTvxTZ66hKOP/Sg=,iv:zSIi56Qkv5LO06CYauL1zbXvC9LXven4aVUjBMfQht8=,tag:A58ACL/pGKeSZYSCo5Jqlg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
