# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-operator-secret
stringData:
  client_id: ENC[AES256_GCM,data:7cP1fuYws9KrUbZRxFfyPbA=,iv:VReR4EfOXK19q+JfYGPgR6R+o6Bu6GX1KHPjIEILajU=,tag:mR8mPhqYzgNZdMZVHUAYtw==,type:str]
  client_secret: ENC[AES256_GCM,data:NZbNR7mdDtSWWr2jY6ywhjqxIVd2BwCfM2RSifmWBmMvYNhNzi5K2r6QQBTMiMzUJrpQd7DRmStBN5XyNVu8jg==,iv:6UEI1Jpn2/4ac5VGKPwHYAWei1yuL4zSIRRdoVwB9ig=,tag:8w8regAqfbHu96m3KpfjGA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOW4zQXlKR1ZlSXE1YXZO
        SWpDeEZuUCtSTEk0YVJkaVZndFdPL25na2dRCkZyVk9kUXdlK2tEUUNIdkZlVzlL
        T29jRlVNMlNXSmptWXdHbkhyaWcyU28KLS0tIGt5MnFpK3lzclB4MUNsOU5zSHVY
        SUplWnZPeGhsekNQTHp4Q0dwakpCMVUK6CbOYO5NTn94bNvjgo0HCAm2NFD7OUSr
        joXAWEhpbdA07QJw127Ct80WeJK2rKrQQgOMzZziWYXU95GqpXSX/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-29T19:43:52Z"
  mac: ENC[AES256_GCM,data:8vnmmUJcas39aWvsOfRv0vStuBqs4oJRY6MbWwYKv0qLZI9/kdEfHWemhPdMKE30d/JPbpEA/j96Ugyx18dx13l7z0C9KDglrSgH9U+Ep/3CtHmRdn0iGrRAC0JS/NzSlykhvZ9S8Cr0KbURBlXCItJ8XfjQgIrFpWCyJMNmdZY=,iv:24qVJs1H7oPaeuTl7Et2lkG4I6iV5Z97yLRHS39JMrw=,tag:hs4MkKap0OYftymoSGoyyw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
