---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-operator-secret
stringData:
  client_id: ENC[AES256_GCM,data:v1li4le5l+YBhyhr9KzdgEU=,iv:Ueab3kI4JsecYuW3brlCRxRJGqPiHpNzNwiHh/I6mQc=,tag:3etMnA+jEzABpRqO32UwZw==,type:str]
  client_secret: ENC[AES256_GCM,data:aJ8IPkgjEpvQdkEsvtvZBZdcEQyhJobqlZX4B6lY3aQYJl5xjhz7WTjo+GCMD27z1nfrTrTB74G7eCbzAUYE0w==,iv:POmzJx3Qbl1q9DkSopcYUB//ljs8LcLmnde7quicUuU=,tag:EiN3YDhKxjkpmVo1VowXog==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWnFzN1Qwa3JZdDdvdjhV
        NE9mM050b2FvcnFxZlZ2U05qWUlGSkxSL0RBClc5VmtibGsySUo0RzRZdmRGWjNG
        N1NzSEs4T3FCSlZmZGtkMW9GMVQrUWsKLS0tIC8vWEo5V0xTMjBnaHBCdEpqMzdM
        UjZkbXBDSDVxM2lINjRxZDFOVWdUKzgKAHDkTT/cJCzwPrRSjGpkS46L3WwD/LBH
        kiHtybw7UKOk9698mUOY9o3qPS9x0tLsEPpuhmCn/5CIzdFH+mi/6Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-15T14:30:52Z"
  mac: ENC[AES256_GCM,data:mHuDWpO1czvn7UEQkflQ1HMzxUfL6EcvONq9foertf2okHDw0eT0ePFI7O2NUYyESTvZCjsrAdGFBltm/SSejt1qhK0Pw8+RClFZrghEHgazZLg2X1wpw3GmDmvls7u+zAed0r5i0pnARsuARnBBYSseP8B/iUDwVde9vEofAqg=,iv:JmMABCN9k8i1BaK1JStLOmjbv6Wclqqs8SMO69c6URE=,tag:LI55SaswEDSieSZwq3y/Sw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
