---
apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: immich-interceptor-route
spec:
  target:
    service: immich
    port: 2283
  rules:
    - hosts:
        - memories.harissaeed.com
  scalingMetric:
    concurrency:
      targetValue: 100

---
apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: immich-machine-learning-interceptor-route
spec:
  target:
    service: immich-machine-learning
    port: 3003
  rules:
    - hosts:
        - immich-machine-learning
  scalingMetric:
    concurrency:
      targetValue: 100

