# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:gO6lYlTN,iv:OG0NLLeCGksNcSQ5F8Lsl2YD6/9u8QcUviEqao9Ij2M=,tag:HEpHiB+hDs3/oXC7HiMfVQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:3XfFwuYogr7tx2eJF8cyETfs/HgLRTBn/cDyRpcH7ecZ01dxQ69InbICDWuulySbdtytnQ==,iv:P8cqW210+me2LCWOd0033dlWAYOV4zTAXYWq/CoPSXY=,tag:JjZ8yTFZQIXbujLmi/KtEw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:UcL+igYvoo0=,iv:JNWeC5iXstAOtSWBtk9FwmFtR6ZhQyQvwVAyKN2Lcgg=,tag:dFeJaEqI0Gqe+JANH4VslQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:BLs8c3ETYNE=,iv:tFYNkyyY9+OI8xR1MbkgOd4WB9WJFQtYpY7g1Ipl0yM=,tag:h0G6hsENrzoK+TEFrRXg8w==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:gWEwcNbnFAwX8ff9,iv:BtutttD2CzC1RbUq/hstdKhc1J5euMiu72I6ogRYSy8=,tag:SxehH45yQHvTCihicKpyCw==,type:str]
  INIT_POSTGRES_USER_FLAGS: ENC[AES256_GCM,data:OUg=,iv:CXAK0p4iFD36lMyib9YebAsi/GkMOX4LIm5cY5suGSs=,tag:vhLxt2+1K0C1VeiXeDSFbA==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:MYnMDpAqEGo=,iv:lTlHEk86vRqVB+LQclbZUD7sE/3IsFLdrqGGfc5KOII=,tag:cA1ek/qciDeilPmgkOA4PQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:Gu7se2m3w98=,iv:FY3MVEMoBk9vdNPaESSW9BOR37swH1lC1Ny7Un1fVvQ=,tag:b9Kp6KyW40zYJ2I9z58pVQ==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUUdsSXRoQWNNam9kbm1i
        MlZia1hEdXVnWlZnM3FLZ25rTExVbVFUL2pVCmRTRm9HNjBBRjRsVnJPeCtOWi80
        SGIzMFpSWlFteXVCZ0RJbHpZcS9IWkkKLS0tIEkwZUdWL2xUNXhoS2RuQ1BrVFd3
        c3BEWElHSmRxQnBtRWN3b2tpcEQwUkEKs4M8ze/5sIFHSPcQX2uAsmDsokeJkwCG
        6JzhH65Cbo0GFvwRc+vbJJuHhqRFX8SFA1qs0p7t8Lh/T/paRMey1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-13T18:52:10Z"
  mac: ENC[AES256_GCM,data:myoLL1YIfe8WXnWwYliPEi14D76hzXbAM0qMCxU/y2bjfDl2B0CeGlHzoOjAputbGuhJ5WpZFwuA6JolRqJkG0M2MHXPEsKl+vchzhbGlgRVE0FCkJJvu74o//eAD20muWiGmvugt2kpVY/t0K6qLhX7gk2VHpDFDTc0fwkInmo=,iv:7eD244h9H+Zq2DC7nRgSbI8G9KF8JShSPTNJA3Gh9jQ=,tag:YseNop/8CIN/FlpPzqePag==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
