# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:tL/aVnES,iv:YK4Jli75PZTJay3gCAd+LuGuYmx890R+kaVTZ6RkzHA=,tag:QSKid5IUtgIHdlfNriHMnQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:GM8T1qrQoCYiMkNk3R5aAwSmS8cXRjFTfxSnHhjejEg5ITpRpP1ZYQWiNowIhEFiNSOroQ==,iv:lpHgm5qZSW2QxrbE71DxInugqAalZ0j9sbdybbqGUgY=,tag:6rxDsQY4dCtMZvPprC97nQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:3foGAZV2ru0=,iv:x3tN37qkklbpBLHezgN5olwXmAabGB0P4gyHEWUyekQ=,tag:WDaIBRwg89ksWPvUqF4FYA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:a2hHySAVoe8=,iv:JBJxT9hWyOfjqUOjQPvCqHPlu2GxO/GnCZMarXc07RQ=,tag:0Gwp+UlsMHAb3RmBw6XraA==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:cmRgBEgFVCtls732,iv:ti7SMTO/OUZTrCXit7JgYBtVwUTrPDK2dF9W1zgi+PU=,tag:rNQ9xh2eCXivfVekbYNagw==,type:str]
  INIT_POSTGRES_USER_FLAGS: ENC[AES256_GCM,data:plc=,iv:F+Cmfh09o+f/+i+agQE8GaOq8my3wQSokyupovjgUNw=,tag:UgF7gqmAWg6nYM96tZAuQg==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:QsBiQsjh1EU=,iv:HiDqKgboaCN70F9yABgeplTvx6Z2WIa9ImbmggFffJw=,tag:vkqT2ZibF5XMdXEcx86Izw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:f8zIaU6wzX4=,iv:CPXWttZciT0T1qGPz/BxIDcoGTTiPeUCE5lvZDq+M2k=,tag:DP99QaXx8APmK0k3/hBMcA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldmJIUFBuTzZiWUI5SVJX
        YzVTeU90VzNEOGZsYmp5YTZ3MWtUb0JQSEhzClQxa2YrOTVWaTNLdzdSZ2pENS81
        RVMzVytvU3FCb1BaMTZZMFgrTUxtUEUKLS0tIHdwMnZheFpkMFRJM3FXcXBXRTNH
        R250WW96L1FkRWJDdUxIZnhjdzUwM28KA5y2Kk7Pw9RTysfZ4tTkwgIwjYqjXSK1
        vHlJLkR4NZzaJ9/TnEtGRciEum2DAtFO9i0S+8CKdq7Yn74zfXR1EQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-15T04:37:46Z"
  mac: ENC[AES256_GCM,data:dCuGjqNfDl6WkI7V+EHZa3RSvPbE3Z532asA8IVpW+MRIlR1abQe6hIangaV85e3LPtiTU6cwQoH0hktkxVqsp6r0GDXm/Zpiu9oNMJ1wY2FDL5B94zTqskFBoddnf6LfAK7KPKwy9GyQ/m7OOvz7cRYHkJCBAX2hGMeAun9kqA=,iv:O30WO/g2fqRPhjFNd4L7TKPM9fPpIvRK4r5NadAqYYM=,tag:GWQN7VGfhLb0u3oS40Ichw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
