# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:gesZemh5,iv:o7uRJ1H+IKEstG1uwb2gxXEnX+4rcS/eknQmhRmxvIM=,tag:cNqR6+SbZuAHRcRGWNAatg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:hQ6HBhFLIp5LS8dGxTKZ5B0kRUJ2yEwWDh2yRqiWw8IIAi5IEqklrZ79i2bUKDBBIIsWSQ==,iv:G1lOxWktq08Bph+Rhgk2y/Wua0sgeM/OJQX/amZP1Fg=,tag:SGW+avW9dkHRna7Zc3xpQw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:oRNHi7Q4TNQ=,iv:JN3eqtXHtPLdWwJXNk3wzhGgJV9wpu71GJ0Cn0uwx70=,tag:jHf7XVidA1ilsxwZjlQjvw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:O+gY7DYESZ4=,iv:D0eJ1oQ4oCfOF9/VWo75QXMcvO0fQV4AbCpQmG3fGv8=,tag:eMF4/npAW30Vpi34TthPZQ==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:xThCNeKBRVBkseDs,iv:rlwC8XACB3NoT5KoPjVqiNcq1tjEYjLRFB0uS+hDP0Q=,tag:whHJWgRSbDghucmPZ2LkVw==,type:str]
  INIT_POSTGRES_USER_FLAGS: ENC[AES256_GCM,data:h+c=,iv:+4XNjcCvs+8wtketlGbB2jDF3FKSSl7p6aonQl/RXCE=,tag:ga0aUUkUyJ+K+uZmkUuMbA==,type:str]
  INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:WghwzuZ1C94=,iv:aFEmMhi8QEojuaAOVV6ZlhksNHNOzzo1QUO7I9vc1MQ=,tag:ehZw6hyGU+T0TSyi4xT/6w==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:APYFhxwmGPM=,iv:LB0Dy4DoIgFthxG1tCAFfX/cRupPIWJAVh3ZyxnAblg=,tag:C2I/t16gwEUhPUVJfpAf8Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUGtMeUEweTIvdzhBbmdU
        aFJKY2gzbFNCSzlVQXQ4V1pWL0hyZHNzQXdBClVnaEhIUmxwelpvMmZ6TG9haU1q
        aXNCdFJtSmFrWWQwS3VUNzNyaFVGSE0KLS0tIG9oM1BPVFduMzhLVmFVVjVOa2h1
        VW1nUkQ0NzhXUGEvY2RvS2ZPYlZ0WTgKgmCQQfs2BZ5na8zbhzqWHRSQfRojLVLs
        0JZuTRNDahdzhgj/OGsDI+s+8YvbAOHLFmMopSEL53FS+lgQYVOeDA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-10T16:42:47Z"
  mac: ENC[AES256_GCM,data:ELasJVnUanXD0fpDotPkRnufbHwU5cflyOIxQoLwJIIbWJg4MEbHMPP7sGJnsBQyDdtgRPVafBf5ay6OpYN2H4hjL0N87AN/I1VRjlqlyEKZgGxtZDV+SdxIAuHq7Cb2dDB9lIDHNtJq9ucgIUEIJl+v9o3JxiraQcwWN8JzoMQ=,iv:zwry7If4q+vonnmCX5bfJ8Idtkwt4P6F2JTYcnb+SHU=,tag:7o1j9Cf2zwoorLRpjCBiwA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
