# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
stringData:
  password: ENC[AES256_GCM,data:CsGhKpXGjPUor9ja,iv:YtX7VB3j2VtCIouAM037H2j7AKMJyPWWQl46Nhtdpnw=,tag:RTvhIwPga0o6oR4P7r7p5A==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGR2tFRW9DQjZFdkZKd1JX
        bzB6Z0lRcHNidFFsWXo4UXNWNHJmT3plakdVCnJibVkvSXNBUjFSMTdEZFR0Z2Vk
        KzRJRk5sM0tzdE9YOWpUZTRUY2JYcTAKLS0tIE15N2ZMSEY4Q3NQUzBWa1dzb2xs
        RHZJVE1nV01wNm4vN3dtcmZlcVExZDAKq+7yC8nlJdxywSRefNc8IfeM7ZV9xOmJ
        3iiZlBfXmKvThYygLImEy/oM+uSjQ4dYdxoqfP7Znoz/Yb4gFzyQTg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-13T18:52:10Z"
  mac: ENC[AES256_GCM,data:R9GhA9GxZ/4HJy/eUlZyBAnUvGkY4arxjpTuK78ZnjHoSP1DvMN1/5xMfHkLp9oS8nLcSYEm2243zQFcsFHvMN1kRaJI9y4UXb7S0clBiLRQy5bnkkaMIVJIi0/BXN4SWD6hNqUEJ/WTpMpXrKpn9ncARPuNQj0onX819OAlQFc=,iv:1XzLZMEtVT4hO6lRLmTqSDwrvSpOmdaB1xKzXAGGtWI=,tag:Hz7OKyVjUU8KgmcdqPycRw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
