# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
stringData:
  password: ENC[AES256_GCM,data:veKJ00RO6YLCOgdh,iv:o6I6QnARINLbyaIH20CD4+ZSpVyAz7lVmZBLZ8tMYa4=,tag:OfdMi2ZUiDf/P9OoZ+OzOA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VlQvY1B4YTlQSk41NVdZ
        TTEzc21UaVNLbjIwNjlYMmFNelNUU1BKMTN3CnNFc3NuRDNnZytOVk9Pc2N1YVpL
        cHN4TFB2Vm9hOXMvSXE3WTdvNzVvNTAKLS0tIHUxR0MzUmhUZHg4YXY4b0FNSmZ2
        bU9tK1JZcThvZXFHckl3SVZrZnlVTzAK8Ee0+2UDiFKinYtYkblOVW0A5DN2eQsA
        nsA8nZCprS0/tptztZzCZTpdnIUkR1XaIQqqK9LvXldqWC+TBBI/3g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-20T19:42:34Z"
  mac: ENC[AES256_GCM,data:JHSmfCmNvzOqiwoCAdRu39Qvlaj1QXerofsalXVFMxiW7FAzhixoGbeqAITQqIVnHUVEjFOwwJGc3S2FZoYR5ffS0ZVGjUP4DUiCtc3HlAoKJ6ox5Yesg4aB3WooCgBNx8uLLCox7BzWTmyrPXbc4Cr9Sk39e6Bk+2EiVUtM63M=,iv:x0jUPbwLfaXDUgV6n1Wu+ljfH/e0FQgNSaCND5mTjKs=,tag:VxAWs4cgEx0luIH7gyWtOA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
