# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
stringData:
  password: ENC[AES256_GCM,data:wcOzEYRkX2LCNbfj,iv:uA9RvxiBKJSMJKcxCs0lVkEJnyvWQqia6108k0ZS358=,tag:fVmgN8MKkWukT8G/FTIUjg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjOUVMQ2xGMy9VT1VQQXkx
        N282WWs5SUkxZjZXbmx6SmhrbXpJc25hU0c0CjFPMWJNWlJ5THEzNWVSQVZ3aVZl
        aTB6WUtWTlgyRjZjWnZZOWxlTlcwRG8KLS0tIDZVZWFCaUwzOElKaU1NWDkrRHpw
        dVQrRjNlcFdVMFZiMGNZNmM0OWhsVWcKgMmTS6Rgxlzd82LTbqcv4sjm94MRN1Pg
        V0O/JwHvWtB47/wHtdcwBByBZwDDbdTJEHEWFTovbGhLmXIOGaSV4w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-19T19:35:04Z"
  mac: ENC[AES256_GCM,data:NWpZJZi6p+sEcSGjieUSgz9pg0pH+SjejMGMTRTORg+fsS/qdxjFJzynkNygW3vdxAmlGvYAO25haZGfmJ38Rqa+Paa93y2ZxtO3n0BZApDH4iJV8AW1j0lNhFkVnc95uNWOpTJ6f+EA6dATCWxlw/LpiuEMgNacsXkAiwALH/E=,iv:7Y+zRpLCja3Lh7TU6cmwMoTz9NGLvvHGj3NG1IV1cWg=,tag:nsJNDJ/guefOUbMZuC6Knw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
