---
# yaml-language-server: $schema=https://kubernetes-schemas.ergho.org/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud
  namespace: databases
  # annotations:
  #   cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-minimal-trixie@sha256:bce3928d510a7c54ae2bc09034f4e997b5deae15f539b82583ee45f2b13d0944
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover

  storage:
    size: 2Gi
    storageClass: openebs-hostpath

  resources:
    requests:
      cpu: 40m
      memory: 540Mi
    limits:
      memory: 2G
  superuserSecret:
    name: nextcloud-pg-secret
  enableSuperuserAccess: true

  postgresql:
    parameters:
      max_connections: "500"
      shared_buffers: 512MB

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true

  bootstrap:
    recovery:
      source: origin

  externalClusters:
    - name: origin
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: garage-store-recovery
          serverName: nextcloud
