---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: gluetun-secret
stringData:
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:1EhaqzYryzqOTYCjdTVNkTI0HFk3R3m/8LtdISYvAK3aRU1oOHyZ/YR6tkA=,iv:jrdPXFYLGDKxrGa4xa7LJJ0+yvfm50IqLQWisKYQNr8=,tag:7mHCiVvXjZ4J0Qy9dYIRUA==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:GdpiXW+c2rSkR0Y=,iv:TKI+Zyit5wNe+LwLYpV0ZIQ/AtVahqdDazWJB+2pGlQ=,tag:rxVCf70D3vISXVWk4Jg3qA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMmJnekJZUzZDV3NEUmZN
        Wkg2ZmQxaUI3NXo3aUo3Q1dub2tJZzBxSEhNCmk1YlhuRW42R0RyaS9sUmI4Mzc4
        N2V5VWU0a0FKdStxbG84M2tTNnhxUG8KLS0tIHNFbGNzUktaVkQ1MGtwdlNqNTc3
        dXJsQm9DT2xyekhJMG9sWUw0eG9DYzQKH+m60IBu8AAaXsveM7hben+yp3RbmB+t
        5jmUju9w/Wxoy8pn94frMQ0mRzuxS3aYbRIGztMQxPanYf/WcQTFHg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-15T14:30:52Z"
  mac: ENC[AES256_GCM,data:TF5bNsY65mW9Nlnm7iEFkqamJDeOSPSqgAStANmW3aiThx8GfpyVilNgf29j5AL/Jq4BmFW+Bv6dFlzEu6Ef7buFAB+qb1XlU9rf2aPS41Ihe+9ID8YzrIfQkV4mdX1h7v8z+0OMZqkLYGOLFZqEdweGxR43WJLdZOZwxb+WFjw=,iv:RjWfLgKptmLn7G4RG5ZlRNAPvnrSvKgKBTI2WzJ0NuQ=,tag:4kFawTwRnild+XKeapegAA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
