# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: gluetun-secret
stringData:
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:l4J/K+Ifi2ucrcqHXsnZZBZ0qKWRePuvT0YIon9tKarEh1w8ZOYOCZ2gX5w=,iv:/8mF6K9orMUMBucr9UkXxuyjxymFJODbAt/InrzNNw4=,tag:wgJFKO0vXBuUypUan0rV1Q==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:NLH4Pi6LuApYw4I=,iv:nrZehYyTRnsSN1WDcRbQbbGUdSmzpFFA3U/bvyMMrls=,tag:IDlNhxtbI1GpRqH9XwQTIw==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWUgzdU5vNTV0MUhsY3p3
        VUJML0JmRFdTWGRjRmRtSEdDWVNXWXc3OHpZCmhtTFpyZ1FHbHo3VndmcTlkc3ZQ
        RlhrOWpoTS9lZjkwUmlnZWJiZ2IvbGcKLS0tIEU2Uk5sNGpGOWV6WmJGeEVFREVx
        Rml0N21uUmp3clFtcnVySFhvMEwrb00KiNdTKcTEgh1CQX8s4xIraQ7ZE5cu8So1
        n/w8fm+h3OQE/UNNZS6sfAn/hQy59m8cuXDJAAZNxZ2ktSdhGylISQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T20:22:42Z"
  mac: ENC[AES256_GCM,data:1DsLfbLHsscrpp0UC5M+/PZXQrmjUJe69Tqv4+Y6r0+BErzTn0/xPgXcenekYV4E+cozq8Z/XmnJiACnErjqw3riL9h8LEU24UXA0hDIxmws4wPlHqhntyK/GTEjjWrMxngU1br4f+ujBd6LAgcPVd1FqqtCNqNmcgO6eldcsnQ=,iv:BsQHCmfiJID6jly2bj/c8CTSpP6Lf9SRJQu7gT+UJOY=,tag:nc2yJhQ8D08XQHNT0rs5Xg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
