# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: gluetun-secret
stringData:
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:U5dvryf8bzm2GahCN2IlDKQZZFQx4l2EF31o1c8Q+ibMoOuBg4N8jocue9E=,iv:cqa0zlvQ4s57hlZbZNTg0n0b0X9lrCAe1hbiFArHx9Y=,tag:zDemHrc3z4Dv2UyTFbBptg==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:qXk2na5VR6UUzEE=,iv:sLkn7Q1tvMLSECc3CqLDgb4MudJQtw962Ep4fIpKiEU=,tag:2gkR08y6bQhWNk9RmvIYKA==,type:str]
sops:
  age:
    - recipient: age1qqmn3056l9z5v4z6c74nkvlrz43ndufqk6q6w900qmtku9t0g98s77hw7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRFQ5dlVPOEJ3bS9sN0RZ
        UVVxaDd3dFRnckdVYlNqSDRvSDcweGRrNUZFCjZ4ZzhLVjFBak1TRi96UkJreHBk
        SkF0UlBsTGVWMW8xN1dIRkRVUlZBa1kKLS0tIHZ2N3JsekNJZHA0Qk9zVk16Ykxx
        UmV5U0dFR0Z2cHJhWVRIYVhMRi9ObjgKT3BAoiI3W9vt6vnRHPIz40EDIU/Drg5q
        gj/F0mKVsS9hzo7dd/31VuhP+3HePcxojayG2PEMVUG4AYl3XXX3Qg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-02T22:25:22Z"
  mac: ENC[AES256_GCM,data:egavReu+eRBHCatyJsHlq8a0V4UFeTobuXxMH8QXQPrkCEtCg6bbx/h6Ufd3lOdRp1IksZ9wsrsvXRe6pYGRYw8JwtLwfjhYJ8apqxExCKhI5tIZIkKaU7MAtlJoEAcp62/F9b4QlslmPLYFCvER0eP6vnjRvMEyEblci7pK+2E=,iv:Bknjiy4pMT+NrytrfPugmjE3HZh6Hf9/W0ficuMBZW0=,tag:y9QrD32Iqzhn1v8VQnPVlw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
